### ISSUE TITLE
Explain edit http-proxy instructions in README

### ISSUE THREAD

**Issue by chrispsommers** [ipdk-io/ipdk#10]
I suggest to edit https://github.com/ipdk-io/ipdk/blob/5e737af4c302013d5a50a5fd287ed43ec8366ef4/build/IPDK_Container/README#L40 a little better, folks are having trouble with this step.

In my case, I don't have a proxy, so I edited `build/IPDK_Container/docker.env` to comment out the line as follows:
```
#export PROXY=<Your Proxy> 
```
Likewise I ignored the already-commented-out lines in `IPDK_Container/start_p4ovs.sh`:
```
#export http_proxy=<your proxy>
#export https_proxy=<your proxy>
```
To be consistent, why not comment out the line in `build/IPDK_Container/docker.env`, then provide instructions for editing if a proxy is required, which might be the exception case anyway? Thanks.

**Comment by n-sandeep** [comment]
This issue is fixed and merged to Ipdk repository.
https://github.com/ipdk-io/ipdk/pull/14
