### ISSUE TITLE
Broken link in README_DOCKER.md

### ISSUE THREAD

**Issue by stadju** [ipdk-io/ipdk#105]
This link is broken.  https://github.com/ipdk-io/ipdk/blob/main/build/README_DOCKER.md#CLI-configuration-settings

Install the IPDK CLI and set your specific IPDK CLI configuration settings! See [here](https://github.com/ipdk-io/ipdk/blob/main/build/README_DOCKER.md#CLI-configuration-settings) for more information about IPDK CLI configuration file settings and inner workings!

**Comment by stolsma** [comment]
Thanks for reporting this! I'm still busy with a PR that has more documentation about the configuration options, will fix this link also. I expect that it will be ready around mid next week!

**Comment by jokuniew** [comment]
@stolsma hi there, any updates? There are still TODOs in CLI configuration settings section :)

**Comment by jokuniew** [comment]
Isn't this section https://github.com/ipdk-io/ipdk/blob/main/build/scripts/ipdk.sh#L499 a solution to this ? @dandaly @stadju

**Comment by jokuniew** [comment]
CLI description link still broken when `./ipdk install`

Path in runtime: https://github.com/ipdk-io/ipdk/blob/main/build/IPDK_Container/README_DOCKER.md#CLI-configuration-settings

Correct path: https://github.com/ipdk-io/ipdk/blob/main/build/networking/README_DOCKER.md#ipdk-cli-configuration-settings

**Comment by stadju** [comment]
Broken link has been removed.  Closing this issue.  @jokuniew please open a new issue on  ~/.ipdk/ipdk.env
