### ISSUE TITLE
Looks like ipdk head (ubuntu2004) is broken

### ISSUE THREAD

**Issue by aravid-marvell** [ipdk-io/ipdk#109]
Fails on both `x86_64` and `aarch64`. 

    root@asaf-pt-dtl0792:/home/labuser/ipdk-io/ipdk/build# ./ipdk install ubuntu2004
    Loaded /home/labuser/ipdk-io/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    User changable IPDK configuration file is already defined at
    '~/.ipdk/ipdk.env'.
    Changed runtime environment to: ubuntu2004
    
    As last step execute:
      export PATH=/home/labuser/ipdk-io/ipdk/build:$PATH
    to add the IPDK CLI to your path in the running environment!
    root@asaf-pt-dtl0792:/home/labuser/ipdk-io/ipdk/build# export PATH=/home/labuser/ipdk-io/ipdk/build:$PATH
    root@asaf-pt-dtl0792:/home/labuser/ipdk-io/ipdk/build# ./ipdk build --no-cache
    Loaded /home/labuser/ipdk-io/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    /home/labuser/ipdk-io/ipdk/build /home/labuser/ipdk-io/ipdk/build
    sudo: jq: command not found
    Job for docker.service failed because the control process exited with error code.
    See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by aravid-marvell** [comment]
I'll try `apt-get install jq` and close issue if that resolves it
Will update soon

**Comment by aravid-marvell** [comment]
After that and a reboot, still seems broken:

    root@asaf-pt-dtl0792:/home/labuser/ipdk-io/ipdk/build# ./ipdk install ubuntu2004
    Loaded /home/labuser/ipdk-io/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    User changable IPDK configuration file is already defined at
    '~/.ipdk/ipdk.env'.
    Changed runtime environment to: ubuntu2004
    
    As last step execute:
      export PATH=/home/labuser/ipdk-io/ipdk/build:$PATH
    to add the IPDK CLI to your path in the running environment!
    root@asaf-pt-dtl0792:/home/labuser/ipdk-io/ipdk/build#   export PATH=/home/labuser/ipdk-io/ipdk/build:$PATH
    root@asaf-pt-dtl0792:/home/labuser/ipdk-io/ipdk/build# echo $PATH
    /home/labuser/ipdk-io/ipdk/build:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
    root@asaf-pt-dtl0792:/home/labuser/ipdk-io/ipdk/build# ipdk build --no-cache
    Loaded /home/labuser/ipdk-io/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    /home/labuser/ipdk-io/ipdk/build /home/labuser/ipdk-io/ipdk/build
    {
      "experimental": true
    }
    Job for docker.service failed because the control process exited with error code.
    See "systemctl status docker.service" and "journalctl -xe" for details.
    Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    docker experimental flag not enabled: Set with 'export DOCKER_CLI_EXPERIMENTAL=enabled'
    Use old docker build!
    Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    /home/labuser/ipdk-io/ipdk/build
    root@asaf-pt-dtl0792:/home/labuser/ipdk-io/ipdk/build#

**Comment by mestery** [comment]
@aravid-marvell Is this on the arm64 architecture?

**Comment by aravid-marvell** [comment]
No, on x86_64

However, this seemed to have resolved it:

    [root@PT-DT0647 build]# ps axf | grep docker | grep -v grep | awk '{print "kill -9 " $1}' | sudo sh
    [root@PT-DT0647 build]# sudo service docker restart

Probably a local issue

Closing for now
Will reopen if becomes relevant
