### ISSUE TITLE
List of packages to build and run p4sde 

### ISSUE THREAD

**Issue by vishalShetye** [ipdk-io/ipdk#120]
Hello Team,
The Dockerfile ( at path ipdk\build\IPDK_Container\Ubuntu20.04) contains the list of the following packages which are getting installed using the command 'RUN apt-get install -y'
RUN apt-get install -y apt-utils \
    git \
    meson \
    cmake \
    libtool \
    clang \
    gcc \
    g++ \
    autoconf \
    automake \
    autoconf-archive \
    libconfig++-dev \
    libgc-dev \
    unifdef \
    libffi-dev \
    libboost-iostreams-dev \
    libboost-graph-dev \
    llvm \
    pkg-config \
    flex libfl-dev \
    zlib1g-dev \
    iproute2 \
    net-tools \
    iputils-arping \
    iputils-ping \
    iputils-tracepath \
    python \
    pip \
    bison \
    python3-setuptools \
    python3-pip \
    python3-wheel \
    python3-cffi \
    libedit-dev \
    libgmp-dev \
    libexpat1-dev \
    libboost-dev \
    google-perftools \
    curl \
    connect-proxy \
    coreutils \
    sudo && \
    apt-get -y clean all

Would you please reply with out of above mentioned which packages are required to build and run p4-sde (p4-dpdk-target)

**Comment by vsureshkumarp** [comment]
@vishalShetye, Please refer https://github.com/p4lang/p4-dpdk-target/blob/main/tools/setup/install_dep.py for dependencies list  for building P4 SDE alone..

**Comment by vsureshkumarp** [comment]
@vishalShetye - Can you close this issue in case you are not looking for any additional information?

**Comment by vsureshkumarp** [comment]
Already provided the requested details. Hence closing the issue.
