### ISSUE TITLE
"ipdk build --platform=linux/arm64" fails on Fedora 35

### ISSUE THREAD

**Issue by x48Jason** [ipdk-io/ipdk#130]
It looks to me currently ipdk build doesn't support cross-build on Fedora.

Here is the output:
[root@x48 networking]# ipdk build --platform linux/arm64 --no-cache --use-proxy
Loaded /home/zengz/ipdk/build/networking/scripts/ipdk_default.env
Loaded /root/.ipdk/ipdk.env
/home/zengz/ipdk/build/networking /home/zengz/ipdk/build/networking
Can't find update-binfmts.
This host doesn't support docker buildx but '--platform', '--push', or '--export' option is requested
This is not supported!

**Comment by mestery** [comment]
Closing this as we merged the fix in #131.
