### ISSUE TITLE
wrong directory of get-image.sh

### ISSUE THREAD

**Issue by qzhan16** [ipdk-io/ipdk#175]
reproduce at commit 45e163a5413e7

diff --git a/build/networking/scripts/rundemo.sh b/build/networking/scripts/rundemo.sh
index 7c7a924..dc2ecbe 100755
--- a/build/networking/scripts/rundemo.sh
+++ b/build/networking/scripts/rundemo.sh
@@ -31,7 +31,7 @@ echo "Creating Ubuntu focal image"
 echo ""

 pushd /root || exit
-/git/ipdk/build/scripts/get-image.sh focal
+/git/ipdk/build/networking/scripts/get-image.sh focal
 rm -f vm1.qcow2 vm2.qcow2
 cp focal-server-cloudimg-amd64.img vm1.qcow2
 cp focal-server-cloudimg-amd64.img vm2.qcow2

**Comment by mestery** [comment]
Hi @qzhan16, it would be great if you submitted a pull request following the [IPDK contribution guidelines](https://github.com/ipdk-io/ipdk/blob/main/CONTRIBUTING.md). Thanks!

**Comment by qzhan16** [comment]
@mestery  this fix be covered in https://github.com/ipdk-io/ipdk/pull/176

**Comment by jokuniew** [comment]
Indeed directory path was changed in #176  here https://github.com/ipdk-io/ipdk/pull/176/commits/9a7896fcb9fedb76227c31888224df1bf51db8ba#diff-600d00426a664ff896e99c453c3589c13469bc23c79bfbf4082c0fdbdd131452L34

Should this issue be still opened? @qzhan16  @mestery

**Comment by vsureshkumarp** [comment]
Closing the issue as it already addressed by @qzhan16 with #176.
