### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by mestery** [ipdk-io/ipdk#19]
When running `source /root/start_p4ovs.sh /root`, I'm seeing the below error. Did something change in one of the dependent P4 packages recently? This is on a Linux VM, not WSL2.

```
make[2]: Leaving directory '/root/p4-sde/p4-driver/src'
make[1]: Leaving directory '/root/p4-sde/p4-driver/src'
Making clean in doc
make[1]: Entering directory '/root/p4-sde/p4-driver/doc'
rm -rf .libs _libs
rm -f *.lo
make[1]: Leaving directory '/root/p4-sde/p4-driver/doc'
Making clean in bf_switchd
make[1]: Entering directory '/root/p4-sde/p4-driver/bf_switchd'
find: ‘/root/p4-sde/install’: No such file or directory
dirname: missing operand
Try 'dirname --help' for more information.
 rm -f bf_switchd
test -z "libbf_switchd_lib.la" || rm -f libbf_switchd_lib.la
rm -f ./so_locations
rm -rf .libs _libs
rm -rf lib/.libs lib/_libs
rm -f *.o
rm -f lib/*.o
rm -f lib/*.lo
rm -f *.lo
make[1]: Leaving directory '/root/p4-sde/p4-driver/bf_switchd'
make[1]: Entering directory '/root/p4-sde/p4-driver'
rm -rf .libs _libs
rm -f *.lo
make[1]: Leaving directory '/root/p4-sde/p4-driver'
make: *** empty string invalid as file name.  Stop.
make: *** [Makefile:56: volume] Error 2
```

**Comment by n-sandeep** [comment]
Hi @mestery,

I have pulled in latest code and tried to build, I haven't seen this issue. There were no changes in OVS code or in dependent SDE code (as the issue is seen while building p4-sde).
We were continuously validating latest IPDK code while working on docker optimization issue, never seen this problem.

Logs snippet:
--------------
libtool: install: /usr/bin/install -c .libs/bf_switchd /root/p4-sde/install/bin/bf_switchd
make[2]: Leaving directory '/root/p4-sde/p4-driver/bf_switchd'
make[1]: Leaving directory '/root/p4-sde/p4-driver/bf_switchd'
make[1]: Entering directory '/root/p4-sde/p4-driver'
make[2]: Entering directory '/root/p4-sde/p4-driver'
make[2]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/root/p4-sde/install/share/target_sys'
 /usr/bin/mkdir -p '/root/p4-sde/install/share'
 /usr/bin/install -c -m 644 zlog-cfg '/root/p4-sde/install/share/target_sys'
 /usr/bin/install -c -m 644  VERSION '/root/p4-sde/install/share/.'
make[2]: Leaving directory '/root/p4-sde/p4-driver'
make[1]: Leaving directory '/root/p4-sde/p4-driver'
WS_DIR: /root/P4-OVS

Any specific steps to follow before running into this state, or Can you please re-run with a fresh pull?

**Comment by mestery** [comment]
I am still seeing this issue while running in a VM. I follow the instructions on the website and it happens every time. Similar to #22, it's frustrating to debug because the `source /root/start_p4ovs.sh /root` command exits the container when the build fails, meaning you have to start over from the beginning.

**Comment by mestery** [comment]
I am trying on a clean repository without my changes from #16 to see if those are causing the issues, will report back.

**Comment by asafravid** [comment]
Exactly the issue I’m facing as well
The container exits and it takes so long to re-run due to the many clone steps
If only the container remained running, I could have debugged and changed files accordingly
Any suggestions here on how to make the process more efficient in that matter?

**Comment by vsureshkumarp** [comment]
Almost all utility scripts enable "set -e" which indicates the bash to immediately exit the terminal.
We will create a new patch for the same.
Meanwhile you can comment the file level "set -e" option and proceed further.

**Comment by asafravid** [comment]
Thanks I'll do that @vsureshkumarp 
I changed those in the relevant scripts under `/scripts`
BTW, in `Ubunu20.04` folder I had to manually copy the `/scripts`, `/examples` and some shell scripts from the parent folder -> Is there a way to avoid this manual copying? In my fork [(https://github.com/asafravid/ipdk)](https://github.com/asafravid/ipdk) you can see that I've copied them from the parent folder

**Comment by asafravid** [comment]
@vsureshkumarp what about the `set +e` at the end of those scripts which have `set -e` at their beggining? Shall I comment out that as well?

**Comment by asafravid** [comment]
Unfortunately remarking `# set -e` didn't help and the docker exits upon failure, maybe something else is missing (like remarking `set +e`?)

**Comment by vsureshkumarp** [comment]
@asafravid, Spent a little bit more time to identify the root cause.
We are running the main script using command _**source**_.  Command used for running the script is **_source start_p4ovs.sh /root_**
I see this is one of the main reasons for container exit in failure cases.
In the main script, command **_exit_** is used in most of the failure cases.
As we are executing the script using _**source**_ command, failure case **_exit_** command directly applies on the container which causes the termination of the core container shell. 

Can you please run by using command _**./start_p4ovs.sh /root**_?
We will update the README in next immediate commit..

No need to change utility scripts.

**Comment by vsureshkumarp** [comment]
@asafravid, No need to copy any utility scripts for building Fedora or Ubuntu containers.
You need to make sure you are in the correct folder and use the make command to build the container of your choice.
For example, if you are interested in building Ubuntu 20.04 container then change the directory to **_build/IPDK_Container/Ubuntu20.04_** and trigger _**make build-nc/build-nc-proxy**_  based on your environment. Make target  *_porxy option is useful if your server is behind the proxy.

**Comment by asafravid** [comment]
> ./start_p4ovs.sh /root

@vsureshkumarp Actually this is the exact command I have run
I'll do that again to triple check but you already state in the Readme as follows:
`Eg: source start_p4ovs.sh /root` and this is exactly what I've run
I'll try only `./start_p4ovs.sh /root` and update results

**Comment by asafravid** [comment]
@vsureshkumarp started as instructed, let's see if it exits upon the failure, will update in ~10 minutes (it takes it very long to download everything etc)

    Successfully built b01a532b5dd8
    Successfully tagged ipdk/p4-ovs-ubuntu20.04:86932d4
    root@pt-dtl3992:/local/store/docker/ipdk/build/IPDK_Container/Ubuntu20.04# make volume
    docker volume create shared; docker run --rm --cap-add ALL --privileged -v shared:/tmp -it ipdk/p4-ovs-ubuntu20.04:86932d4
    shared
    root@545513cf34a8:~# ./start_p4ovs.sh /root
    SHELL_STRING=
    Removing P4-OVS directory if it already exits
    Cloning P4-OVS repo
    Cloning into 'P4-OVS'...
    remote: Enumerating objects: 159350, done.
    remote: Total 159350 (delta 0), reused 0 (delta 0), pack-reused 159350
    Receiving objects: 100% (159350/159350), 103.23 MiB | 9.44 MiB/s, done.
    Resolving deltas: 100% (126429/126429), done.
    Submodule 'external/googleapis' (https://github.com/googleapis/googleapis.git) registered for path 'external/googleapis'
    Submodule 'p4runtime' (https://github.com/p4lang/p4runtime.git) registered for path 'p4runtime'
    Submodule 'stratum' (https://github.com/stratum/stratum.git) registered for path 'stratum'
    Submodule 'switchlink/submodules/SAI' (https://github.com/opencomputeproject/SAI.git) registered for path 'switchlink/submodules/SAI'
    Cloning into '/root/P4-OVS/external/googleapis'...
    remote: Enumerating objects: 166552, done.
    remote: Counting objects: 100% (3639/3639), done.
    remote: Compressing objects: 100% (1232/1232), done.
    remote: Total 166552 (delta 2341), reused 3546 (delta 2327), pack-reused 162913
    Receiving objects: 100% (166552/166552), 156.11 MiB | 22.83 MiB/s, done.
    Resolving deltas:  29% (43444/146037)
    ...

**Comment by asafravid** [comment]
> @asafravid, No need to copy any utility scripts for building Fedora or Ubuntu containers. You need to make sure you are in the correct folder and use the make command to build the container of your choice. For example, if you are interested in building Ubuntu 20.04 container then change the directory to **_build/IPDK_Container/Ubuntu20.04_** and trigger _**make build-nc/build-nc-proxy**_ based on your environment. Make target *_porxy option is useful if your server is behind the proxy.

Ok, done, looks like what i did wrong was `docker build .` instead of `make build-nc`

**Comment by asafravid** [comment]
@vsureshkumarp great, looks like now the docker doesn't exit, which can allow some debugging

    Found ninja-1.10.0 at /usr/bin/ninja
    [1834/2745] Compiling C object 'lib/76b5a35@@rte_pipeline@sta/pipeline_rte_table_action.c.o'.
    FAILED: lib/76b5a35@@rte_pipeline@sta/pipeline_rte_table_action.c.o
    cc -Ilib/76b5a35@@rte_pipeline@sta -Ilib -I../lib -Ilib/pipeline -I../lib/pipeline -I. -I../ -Iconfig -I../config -Ilib/eal/include -I../lib/eal/include -Ilib/eal/linux/include -I../lib/eal/linux/include -Ilib/eal/x86/include -I../lib/eal/x86/include -Ilib/eal/common -I../lib/eal/common -Ilib/eal -I../lib/eal -Ilib/kvargs -I../lib/kvargs -Ilib/telemetry/../metrics -I../lib/telemetry/../metrics -Ilib/telemetry -I../lib/telemetry -Ilib/port -I../lib/port -Ilib/ethdev -I../lib/ethdev -Ilib/net -I../lib/net -Ilib/mbuf -I../lib/mbuf -Ilib/mempool -I../lib/mempool -Ilib/ring -I../lib/ring -Ilib/meter -I../lib/meter -Ilib/sched -I../lib/sched -Ilib/ip_frag -I../lib/ip_frag -Ilib/hash -I../lib/hash -Ilib/rcu -I../lib/rcu -Ilib/cryptodev -I../lib/cryptodev -Ilib/eventdev -I../lib/eventdev -Ilib/timer -I../lib/timer -Ilib/kni -I../lib/kni -Ilib/pci -I../lib/pci -Ilib/table -I../lib/table -Ilib/lpm -I../lib/lpm -Ilib/acl -I../lib/acl -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -include rte_config.h -Wextra -Wcast-qual -Wdeprecated -Wformat -Wformat-nonliteral -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-address-of-packed-member -Wno-packed-not-aligned -Wno-missing-field-initializers -D_GNU_SOURCE -fPIC -march=native -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API -Wno-format-truncation -DRTE_LOG_DEFAULT_LOGTYPE=lib.pipeline -MD -MQ 'lib/76b5a35@@rte_pipeline@sta/pipeline_rte_table_action.c.o' -MF 'lib/76b5a35@@rte_pipeline@sta/pipeline_rte_table_action.c.o.d' -o 'lib/76b5a35@@rte_pipeline@sta/pipeline_rte_table_action.c.o' -c ../lib/pipeline/rte_table_action.c
    {standard input}: Assembler messages:
    {standard input}: Warning: end of file not at end of a line; newline inserted
    {standard input}:692: Error: unknown pseudo-op: `.lfe602'
    cc: fatal error: Killed signal terminated program cc1
    compilation terminated.
    [1881/2745] Compiling C object 'lib/76b5a35@@rte_vhost@sta/vhost_vhost_crypto.c.o'.
    ninja: build stopped: subcommand failed.
    make[4]: *** [Makefile:480: all] Error 1
    make[4]: Leaving directory '/root/p4-sde/p4-driver/src/lld/dpdk'
    make[3]: *** [Makefile:2392: all-recursive] Error 1
    make[3]: Leaving directory '/root/p4-sde/p4-driver/src'
    make[2]: *** [Makefile:966: all] Error 2
    make[2]: Leaving directory '/root/p4-sde/p4-driver/src'
    make[1]: *** [Makefile:522: all-recursive] Error 1
    make[1]: Leaving directory '/root/p4-sde/p4-driver'
    make: *** [Makefile:409: all] Error 2
    root@545513cf34a8:~# <------------------------

Now the question is why it fails... I'll debug. Please let me know if you have any directions on resolving the actual failure
Much appreciated

**Comment by mestery** [comment]
OK, my particular error (which this issue is related to) was a bug in my spellcheck PR from #16. I'm closing this one, as my latest commit (which I will push once I've verified it one more time) will fix things for me.
