### ISSUE TITLE
ipdk container tutorial on ubuntu 20.04: error with gnmi-cli

### ISSUE THREAD

**Issue by xavier-grall** [ipdk-io/ipdk#2]
When trying the [ipdk container tutorial](https://github.com/ipdk-io/ipdk/blob/e9a3b89b33bfa31f185a835598f5802b35c6b647/build/IPDK_Container/README) on a baremetal server with ubuntu 20.04, I succeed in installing and starting ovs without any matter.
But an error occures with [gnmi-cli for interface creation](https://github.com/ipdk-io/ipdk/blob/e9a3b89b33bfa31f185a835598f5802b35c6b647/build/IPDK_Container/README#L96)
`gnmi-cli: error while loading shared libraries: libglog.so.1: cannot open shared object file: No such file or directory`

However, the file is in /usr/local/lib64 (as a target of a symlink) which is itsef in the path list:
```
# ll /usr/local/lib64/libglog.so.1
lrwxrwxrwx 1 root root 16 Oct 27 11:26 /usr/local/lib64/libglog.so.1 -> libglog.so.0.6.0
# ll /usr/local/lib64/libglog.so.0.6.0
-rwxr-xr-x 1 root root 258376 Oct 27 11:26 /usr/local/lib64/libglog.so.0.6.0
# echo $LD_LIBRARY_PATH
:/root/p4-sde/install/lib:/root/p4-sde/install/lib64:/usr/local/lib:/usr/local/lib64:/root/p4-sde/install/lib:/root/p4-sde/install/lib64:/usr/local/lib:/usr/local/lib64
```
Any idea to solve it ?

**Comment by namratalimaye** [comment]
I have committed the fix in REAME. Thanks !
