### ISSUE TITLE
 Failed to start container from pulled docker images.  Also, need how-to documentation

### ISSUE THREAD

**Issue by stadju** [ipdk-io/ipdk#212]
1. Pull docker images as provided on https://github.com/ipdk-io/ipdk

docker pull ghcr.io/ipdk-io/ipdk-ubuntu2004-x86_64:sha-b4cff43

2. Build container from images:

docker run ghcr.io/ipdk-io/ipdk-ubuntu2004-x86_64:sha-948e42e (image_name:tag)

3. Check docker container:

docker ps -a

CONTAINER ID   IMAGE                                                COMMAND   CREATED          STATUS                      PORTS     NAMES

f25bb6d204d8   ghcr.io/ipdk-io/ipdk-ubuntu2004-x86_64:sha-948e42e   "bash"    25 minutes ago   Exited (0) 25 minutes ago             dreamy_hoover

4. start container

docker start container_ID

[root@wp06 docker]# docker start f25bb6d204d8

f25bb6d204d8

[root@wp06 docker]# docker ps

CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES

[root@wp06 docker]#

**Comment by jokuniew** [comment]
Inside ipdk docker run command works with -it `"${ARGS[@]}" -it "${IMAGE_NAME}":"${TAG}" "${RUN_COMMAND[@]}"` https://github.com/ipdk-io/ipdk/blob/main/build/scripts/ipdk.sh#L261
Have you tried with `ipdk start -d` command?

**Comment by stadju** [comment]
There's a 22.07 release package.  And 3 other packages listed under.  Please label/document what they are.

**Comment by stadju** [comment]
docker run -it is working.  Closing the ticket.  But still needs to label what the images are.
