### ISSUE TITLE
Ubuntu20.04, error upon build_p4sde.sh within start_p4ovs.sh

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#22]
What could cause the below failure upon invocation of `build_p4sde.sh` within `start_p4ovs.sh`?

    Found ninja-1.10.0 at /usr/bin/ninja
    [2264/2745] Compiling C object 'lib/76b5a35@@rte_vhost@sta/vhost_vhost_crypto.c.o'.
    FAILED: lib/76b5a35@@rte_vhost@sta/vhost_vhost_crypto.c.o
    cc -Ilib/76b5a35@@rte_vhost@sta -Ilib -I../lib -Ilib/vhost -I../lib/vhost -I. -I../ -Iconfig -I../config -Ilib/eal/include -I../lib/eal/include -Ilib/eal/linux/include -I../lib/eal/linux/include -Ilib/eal/x86/include -I../lib/eal/x86/include -Ilib/eal/common -I../lib/eal/common -Ilib/eal -I../lib/eal -Ilib/kvargs -I../lib/kvargs -Ilib/telemetry/../metrics -I../lib/telemetry/../metrics -Ilib/telemetry -I../lib/telemetry -Ilib/ethdev -I../lib/ethdev -Ilib/net -I../lib/net -Ilib/mbuf -I../lib/mbuf -Ilib/mempool -I../lib/mempool -Ilib/ring -I../lib/ring -Ilib/meter -I../lib/meter -Ilib/cryptodev -I../lib/cryptodev -Ilib/rcu -I../lib/rcu -Ilib/hash -I../lib/hash -Ilib/pci -I../lib/pci -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O3 -include rte_config.h -Wextra -Wcast-qual -Wdeprecated -Wformat -Wformat-nonliteral -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wold-style-definition -Wpointer-arith -Wsign-compare -Wstrict-prototypes -Wundef -Wwrite-strings -Wno-address-of-packed-member -Wno-packed-not-aligned -Wno-missing-field-initializers -D_GNU_SOURCE -fPIC -march=native -DALLOW_EXPERIMENTAL_API -DALLOW_INTERNAL_API -Wno-format-truncation -DVHOST_GCC_UNROLL_PRAGMA -fno-strict-aliasing -DRTE_LOG_DEFAULT_LOGTYPE=lib.vhost -MD -MQ 'lib/76b5a35@@rte_vhost@sta/vhost_vhost_crypto.c.o' -MF 'lib/76b5a35@@rte_vhost@sta/vhost_vhost_crypto.c.o.d' -o 'lib/76b5a35@@rte_vhost@sta/vhost_vhost_crypto.c.o' -c ../lib/vhost/vhost_crypto.c
    {standard input}: Assembler messages:
    {standard input}:1867: Warning: end of file not at end of a line; newline inserted
    {standard input}:3330: Error: unknown pseudo-op: `.lcolde'
    cc: fatal error: Killed signal terminated program cc1
    compilation terminated.
    [2311/2745] Compiling C object 'drivers/a715181@@tmp_rte_event_octeontx2@sta/event_octeontx2_otx2_worker_dual.c.o'.
    ninja: build stopped: subcommand failed.
    make[4]: *** [Makefile:480: all] Error 1
    make[4]: Leaving directory '/root/p4-sde/p4-driver/src/lld/dpdk'
    make[3]: *** [Makefile:2392: all-recursive] Error 1
    make[3]: Leaving directory '/root/p4-sde/p4-driver/src'
    make[2]: *** [Makefile:966: all] Error 2
    make[2]: Leaving directory '/root/p4-sde/p4-driver/src'
    make[1]: *** [Makefile:522: all-recursive] Error 1
    make[1]: Leaving directory '/root/p4-sde/p4-driver'
    make: *** [Makefile:409: all] Error 2
    Makefile:56: recipe for target 'volume' failed
    make: *** [volume] Error 2
    root@pt-dtl3992:/local/store/docker/ipdk/build/IPDK_Container/Ubuntu20.04#

The main issue is that once there's a failure the whole docker stops, and I cannot debug the issue and it takes very long to re-reach the point of failure

**Comment by vsureshkumarp** [comment]
@asafravid, DPDK Library build is failing.  I see **_"{standard input}:3330: Error: unknown pseudo-op: `.lcolde'"_**
Could you please provide environment details if possible?
Meanwhile we will also try to build an Ubuntu container once again and observe the behavior.

**Comment by asafravid** [comment]
@vsureshkumarp - sure, do yo need the `printenv` contents?

**Comment by asafravid** [comment]
@vsureshkumarp if `DPDK` is broken perhaps (suggestion) you should tag the latest non-broken `dpdk` which will result in clean build?

**Comment by vsureshkumarp** [comment]
@asafravid, P4 SDE uses the DPDK libraries  with a particular tag which is working and verified.  We haven't observed the issues which you are facing. Tried to reproduce the issue locally by using different server/VM environments. Somehow we are unable to reproduce the issue and everything is going fine for multiple attempts.

**Comment by vsureshkumarp** [comment]
@asafravid, Tried following possible combinations

1. Host - Ubuntu 18.04 - Docker Container Ubuntu 20.04 (Similar configuration what you are trying)
2. Host - Ubuntu 18.04 - Docker Container Fedora 20.03
3. Host - Fedora 33 - Docker Container Ubuntu 20.04
4. Host - Fedora 33 - Docker Container Fedora 33
In all above scenarios, Host is physical server. Even we tried couple of above scenarios in VM too.
Not even single instance of the issue you reported observed. 

**_Verify gcc/g++/as version_**
Please verify whether gcc, g++ and as versions are matching below versions on your container. Ideally it should match..
root@661fade5060c:~# gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@661fade5060c:~# g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@661fade5060c:~# which as
/usr/bin/as
root@661fade5060c:~# as --version
GNU assembler (GNU Binutils for Ubuntu) 2.34
Copyright (C) 2020 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or later.
This program has absolutely no warranty.
This assembler was configured for a target of `x86_64-linux-gnu'.
root@661fade5060c:~# 

_**Avoid Parallel compilation**_
If all versions are matching, try to avoid parallel compilation. It helps us to rule out any memory issues on your system.
You can disable this in "https://github.com/ipdk-io/ipdk/blob/main/build/IPDK_Container/scripts/os_ver_details.sh"
Make sure always _**NUM_CORES=""**_

**Comment by asafravid** [comment]
@vsureshkumarp Thanks, I'll try your above suggestions and update my findings

**Comment by asafravid** [comment]
@vsureshkumarp 

Failed again unfortunately on clean repository clone
I guess it is a local issue, but I'm trying to find exactly what it is
I will also try this on a Cent OS host I have

    root@1fabb262709f:~# gcc --version
    gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
    Copyright (C) 2019 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    root@1fabb262709f:~# g++ --version
    g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
    Copyright (C) 2019 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

    root@1fabb262709f:~# as --version
    GNU assembler (GNU Binutils for Ubuntu) 2.34
    Copyright (C) 2020 Free Software Foundation, Inc.
    This program is free software; you may redistribute it under the terms of
    the GNU General Public License version 3 or later.
    This program has absolutely no warranty.
    This assembler was configured for a target of `x86_64-linux-gnu'.

I'll now try the `NUM_CORES` suggestion (4 cores on my machine)

**Comment by asafravid** [comment]
I'm very happy to update that on my `CentOS 8` machine, **all is well!**
**Issue not observed at all**
So - seems like a rare local issue and moreover (ore more probably) something specific (0-order) with my local setup (`Ubuntu`)
I shall close this issue unless anyone has objections?
Worst-case -> I'll re-open it if I re-encounter
Thanks @vsureshkumarp for the dedicated help! much appreciated
moving on now to the next steps in the readme

I **confirm** Readme step `4) a.` has successfully completed:

    4) Clone and install dependencies using
        a. source /root/start_p4ovs.sh <any directory>
