### ISSUE TITLE
Ubuntu 18.04 build issue due to protobuf version

### ISSUE THREAD

**Issue by n-sandeep** [ipdk-io/ipdk#223]
Ubuntu 18.04 doesn't support protobuf version 3.20.1,this causes ubuntu build issues. 
Dockerfile.ubuntu should be modified to check if the build is for 18.04 or 20.04 and install protobuf version accordingly.

**Comment by nupurjai** [comment]
Also came across issues with abseil build due to 18.04 default g++ version (std=c++11). Can you please confirm that as well.
No issues on ubuntu fossa or jellyfish.

**Comment by n-sandeep** [comment]
We are not supporting ubuntu 18.04 as part of IPDK release. Hence closing this PR.
