### ISSUE TITLE
"benign" warning? ovs-vswitchd: error while loading shared libraries: libtarget_utils.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#23]
Looks like all is up now, just verifying the below `error` can be safely ignored?

    root@05eb99eb621b:~/P4-OVS# /root/scripts/run_ovs.sh
    Killing OVS Processes If Already Running....
    Creating /var/run/openvswitch
    Starting OvS DB server....
    Staring OvS VSWITCHD Process....
    ovs-vswitchd: error while loading shared libraries: libtarget_utils.so: cannot open shared object file: No such file or directory
    root@05eb99eb621b:~/P4-OVS# ps -ef | grep ovs
    root       87864       1  0 21:03 ?        00:00:00 ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile --detach
    root       87868       1  0 21:04 pts/0    00:00:00 grep --color=auto ovs
    root@05eb99eb621b:~/P4-OVS#

**Comment by n-sandeep** [comment]
Hi @asafravid ,

Have you followed steps mentioned in README under section "Commands to bring-up container and run OvS with P4". Have you executed below step as well, before starting OVS??

5) Export the variables: 
    a.  cd P4-OVS 
    b.  source /root/P4-OVS/p4ovs_env_setup.sh /root/p4-sde/install

**Comment by asafravid** [comment]
@n-sandeep Yes, I have run step `5`. I am ommitting the `source` as per @vsureshkumarp's suggestion so as to avoid the docker exiting upon errors. 

Here are the logs, let me know if you see something missing/wrong there (apart from the benign `hugepages` warning in step `6)` accoring to [https://github.com/ipdk-io/ipdk/issues/23)](https://github.com/ipdk-io/ipdk/issues/23) :

    root@05eb99eb621b:~# cd P4-OVS
    root@05eb99eb621b:~/P4-OVS# /root/P4-OVS/p4ovs_env_setup.sh /root/p4-sde/install
    OS and Version details...
    Ubuntu : 20.04

    Updated Environment Variables ...
    SDE_INSTALL: /root/p4-sde/install
    PKG_CONFIG_PATH: /root/p4-sde/install/lib/x86_64-linux-gnu/pkgconfig
    LIBRARY_PATH:
    LD_LIBRARY_PATH: :/root/p4-sde/install/lib:/root/p4-sde/install/lib/x86_64-linux-gnu:/usr/local/lib:/usr/local/lib64
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    C_INCLUDE_PATH:
    CPLUS_INCLUDE_PATH:

    root@05eb99eb621b:~/P4-OVS# /root/scripts/set_hugepages.sh
    1024
    tee: /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages: No such file or directory
    1024
    root@05eb99eb621b:~/P4-OVS# rm -rf /tmp/vhost-user-*
    root@05eb99eb621b:~/P4-OVS# /root/scripts/run_ovs.sh
    Killing OVS Processes If Already Running....
    Creating /var/run/openvswitch
    Starting OvS DB server....
    Staring OvS VSWITCHD Process....
    ovs-vswitchd: error while loading shared libraries: libtarget_utils.so: cannot open shared object file: No such file or directory
    root@05eb99eb621b:~/P4-OVS# ps -ef | grep ovs
    root       87864       1  0 21:03 ?        00:00:00 ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile --detach
    root       87868       1  0 21:04 pts/0    00:00:00 grep --color=auto ovs
    root@05eb99eb621b:~/P4-OVS#

**Comment by n-sandeep** [comment]
@asafravid 

For the env variables to be set on the shell, we need to run it with 'source'.
In the previous issue #19, it was suggested to not use source, as 'exit' command directly applied on the container and it is exiting the container. But here we are exporting few env variables which are needed for running OVS with P4.


Logs Snippet:
=========
root@1973e8ff1345:~# cd /root/P4-OVS/
root@1973e8ff1345:~/P4-OVS# ./p4ovs_env_setup.sh /root/WORKING-DIR/dpdk/install
OS and Version details...
Ubuntu : 20.04


Updated Environment Variables ...
SDE_INSTALL: /root/WORKING-DIR/dpdk/install
PKG_CONFIG_PATH: /root/WORKING-DIR/dpdk/install/lib/x86_64-linux-gnu/pkgconfig
LIBRARY_PATH:
LD_LIBRARY_PATH: :/root/WORKING-DIR/dpdk/install/lib:/root/WORKING-DIR/dpdk/install/lib/x86_64-linux-gnu:/usr/local/lib:/usr/local/lib64
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
C_INCLUDE_PATH:
CPLUS_INCLUDE_PATH:

root@1973e8ff1345:~/P4-OVS# echo $SDE_INSTALL

root@1973e8ff1345:~/P4-OVS# echo $PKG_CONFIG_PATH

root@1973e8ff1345:~/P4-OVS#
root@1973e8ff1345:~/P4-OVS# source  ./p4ovs_env_setup.sh /root/WORKING-DIR/dpdk/install
OS and Version details...
Ubuntu : 20.04


Updated Environment Variables ...
SDE_INSTALL: /root/WORKING-DIR/dpdk/install
PKG_CONFIG_PATH: /root/WORKING-DIR/dpdk/install/lib/x86_64-linux-gnu/pkgconfig
LIBRARY_PATH:
LD_LIBRARY_PATH: :/root/WORKING-DIR/dpdk/install/lib:/root/WORKING-DIR/dpdk/install/lib/x86_64-linux-gnu:/usr/local/lib:/usr/local/lib64
PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
C_INCLUDE_PATH:
CPLUS_INCLUDE_PATH:

root@1973e8ff1345:~/P4-OVS#
root@1973e8ff1345:~/P4-OVS# echo $SDE_INSTALL
/root/WORKING-DIR/dpdk/install
root@1973e8ff1345:~/P4-OVS# echo $PKG_CONFIG_PATH
/root/WORKING-DIR/dpdk/install/lib/x86_64-linux-gnu/pkgconfig

**Comment by n-sandeep** [comment]
Also, warning from step 6) is going to be fixed with PR #16 (https://github.com/ipdk-io/ipdk/pull/16/files#diff-6fb8451c016d1030602acede627c1b6de124e8d551cc17f394c5584c7fd06f66R16)

**Comment by asafravid** [comment]
@n-sandeep understood - I'll try a re-run of the last steps with `source`

**Comment by asafravid** [comment]
@n-sandeep I think it looks better now, can you confirm?

    root@e0757c2857f3:~/P4-OVS# source /root/P4-OVS/p4ovs_env_setup.sh /root/p4-sde/install
    OS and Version details...
    Ubuntu : 20.04
    
    
    Updated Environment Variables ...
    SDE_INSTALL: /root/p4-sde/install
    PKG_CONFIG_PATH: /root/p4-sde/install/lib/x86_64-linux-gnu/pkgconfig
    LIBRARY_PATH:
    LD_LIBRARY_PATH: :/root/p4-sde/install/lib:/root/p4-sde/install/lib/x86_64-linux-gnu:/usr/local/lib:/usr/local/lib64
    PATH: /root/P4-OVS/:/root/scripts/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    C_INCLUDE_PATH:
    CPLUS_INCLUDE_PATH:
    
    root@e0757c2857f3:~/P4-OVS# /root/scripts/set_hugepages.sh
    1024
    tee: /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages: No such file or directory
    1024
    root@e0757c2857f3:~/P4-OVS# rm -rf /tmp/vhost-user-*
    root@e0757c2857f3:~/P4-OVS# /root/scripts/run_ovs.sh
    Killing OVS Processes If Already Running....
    Creating /var/run/openvswitch
    Starting OvS DB server....
    Staring OvS VSWITCHD Process....
    2021-12-17T10:23:56Z|00001|vlog|INFO|opened log file /tmp/ovs-vswitchd.log
    2021-12-17T10:23:56Z|00002|ovs_numa|INFO|Discovered 8 CPU cores on NUMA node 0
    2021-12-17T10:23:56Z|00003|ovs_numa|INFO|Discovered 1 NUMA nodes and 8 CPU cores
    WARNING: Logging before InitGoogleLogging() is written to STDERR
    I20211217 10:23:56.768301 87865 bf_sde_wrapper.cc:1530] bf_sysfs_fname: /sys/class/bf/bf0/device/dev_add
    Install dir: /usr (0x55b2b5d36c40)
    bf_switchd: system services initialized
    bf_switchd: loading conf_file /usr/share/stratum/target_skip_p4_no_bsp.conf...
    bf_switchd: processing device configuration...
    Configuration for dev_id 0
      Family        : dpdk
    bf_switchd: processing P4 configuration...
    P4 profile for dev_id 0
    P4 EAL args dummy -n 4 -c 3
    num P4 programs 1
      p4_name: dummy
      bfrt_config:
      port_config:
      p4_pipeline_name: pipe
        context:
        config:
      Pipes in scope [0 1 2 3 ]
      diag:
      accton diag:
      non_default_port_ppgs: 0
      SAI default initialize: 1
    Operational mode set to DPDK MODEL
    Initialized the device types using PAL handler registration
    bf_switchd: drivers initialized
    Skipping P4 program load for dev_id 0
    EAL: Detected CPU lcores: 8
    EAL: Detected NUMA nodes: 1
    EAL: Detected shared linkage of DPDK
    EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
    EAL: Selected IOVA mode 'PA'
    EAL: No available 1048576 kB hugepages reported
    TELEMETRY: No legacy callbacks, legacy socket not created
    2021-12-17 10:23:57.323826 BF_BFRT FATAL - Unable to find any BfRt Json File
    2021-12-17 10:23:57.323991 BF_BFRT ERROR - makeBfRtInfo:383 Failed to create BfRtInfo for dev_id  0
    
    bf_switchd: dev_id 0 initialized
    
    bf_switchd: initialized 1 devices
    Skip p4 lib init
    Skip mav diag lib init
    bf_switchd: spawning cli server thread
    bf_switchd: running in background; driver shell is disabled
    bf_switchd: server started - listening on port 9999
    I20211217 10:23:57.325834 87865 bf_sde_wrapper.cc:1548] switchd started successfully
    I20211217 10:23:57.325850 87865 bf_interface.cc:98] Detected is_sw_model: 1
    I20211217 10:23:57.325856 87865 bf_interface.cc:99] SDE version: 9.5.0
    2021-12-17T10:23:57Z|00004|reconnect|INFO|unix:/usr/local/var/run/openvswitch/db.sock: connecting...
    2021-12-17T10:23:57Z|00005|reconnect|INFO|unix:/usr/local/var/run/openvswitch/db.sock: connected
    E1217 10:23:57.342993285   87880 server_chttp2.cc:40]        {"created":"@1639736637.342966751","description":"Only 1 addresses added out of total 2 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":404,"referenced_errors":[{"created":"@1639736637.342948753","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":420,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::1]:28000"}]}
    All Processes Started.....
    root@e0757c2857f3:~/P4-OVS#

**Comment by n-sandeep** [comment]
@asafravid This looks fine.

**Comment by asafravid** [comment]
Great, closing, and thanks!
