### ISSUE TITLE
Unable to run ipdk in native mode with release tar from (https://github.com/ipdk-io/ipdk/releases/tag/v22.07)

### ISSUE THREAD

**Issue by nupuruttarwar** [ipdk-io/ipdk#230]
Steps:
1. Download the release tar from https://github.com/ipdk-io/ipdk/releases/tag/v22.07
2. Follow the README to build ipdk in native mode(https://github.com/ipdk-io/ipdk/blob/main/build/networking/README_NATIVE.md)

Following error is seen:
`root@ubuntu2004:~# SCRIPT_DIR=/git/ipdk/build/networking/scripts /git/ipdk/build/networking/scripts/host_install.sh
...
fatal: not a git repository (or any parent up to mount point /git)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set)`

This is due to the way host_install script is written.
`cp -r /git/ipdk/build/networking/scripts .
cp -r /git/ipdk/build/networking/examples .
cp -r /git/ipdk/build/networking/patches .
cp /git/ipdk/build/networking/start_p4ovs.sh start_p4ovs.sh
cp /git/ipdk/build/networking/run_ovs_cmds run_ovs_cmds`

It specifically expects /git/ipdk. host_install.sh should be reworked to work with release tars as well as git clone

**Comment by mestery** [comment]
It seems as if something is hardcoded somewhere.
