### ISSUE TITLE
IPDK doesn't clean up QEMU VMs in Networking demo

### ISSUE THREAD

**Issue by jokuniew** [ipdk-io/ipdk#235]
# Problem statement
During networking demo there are two QEMU VMs created - `VM1_TAP_DEV` and `VM2_TAP_DEV`.

First of all - networking demo still does not have `stop-demo` method, so the VMs are never cleaned up after `ipdk demo`
If user want to restart demo -> it has to kill -9 qemu processes by itself.

# Possible solutions
1) Add command `pkill qemu` to rundemo.sh around "cleanup from previous run" [here](https://github.com/ipdk-io/ipdk/blob/main/build/networking/scripts/rundemo.sh#L52)

2) Implement stop-demo in makefile just like networking_ebpf has

**Comment by jokuniew** [comment]
Also `ipdk stop` on networking vagrant-container solution returns given errors
```
root@ubuntu2004:/git/ipdk/build# ./ipdk stop
Loaded /git/ipdk/build/scripts/ipdk_default.env
Loaded /root/.ipdk/ipdk.env
qemu-system-x86_64: Failed to read from slave.
qemu-system-x86_64: Failed to read from slave.
qemu-system-x86_64: Failed to set msg fds.
qemu-system-x86_64: vhost VQ 0 ring restore failed: -1: No such file or directory (2)
qemu-system-x86_64: Failed to set msg fds.
qemu-system-x86_64: vhost VQ 1 ring restore failed: -1: No such file or directory (2)
qemu-system-x86_64: Failed to set msg fds.
qemu-system-x86_64: vhost VQ 0 ring restore failed: -1: No such file or directory (2)
qemu-system-x86_64: Failed to set msg fds.
qemu-system-x86_64: vhost VQ 1 ring restore failed: -1: No such file or directory (2)
ipdk
```

Before `ipdk stop` demo was working fine - no network issues or whatsoever

**Comment by n-sandeep** [comment]
This PR https://github.com/ipdk-io/ipdk/pull/273 fixes issue with qemu kill.
