### ISSUE TITLE
Improper quoting in ipdk-lib.sh

### ISSUE THREAD

**Issue by mikeBashStuff** [ipdk-io/ipdk#250]
In `create_images()` there's an improper quoting pattern applied:

```
rm -f "$IMAGE_LOCATION/vm*.qcow2"
rm -f "$IMAGE_LOCATION/seed*.img"
```
This passes `vm*.qcow2` and `seed*.img` as literal strings without applying the actual glob pattern in the pathname expansion. Should be something more like this:

```
rm -f "$IMAGE_LOCATION/"vm*.qcow2
rm -f "$IMAGE_LOCATION/"seed*.img
```

**Comment by vsureshkumarp** [comment]
Updated ipdk-lib.sh create_images() procedure to correct the improper quoting used for removing all images.
Changes committed with PR #266.
