### ISSUE TITLE
Question regarding NUM_CORES and NUM_THEADS

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#26]
What is the motivation of dividing NUM_CORES by 4, why can't all available cpus be used?

 
    get_num_cores()
    {
       nproc_exist=$(which nproc)
       if [ ! -z "$nproc_exist" ];
       then
           NUM_CORES=$(nproc --all)
           echo "Num cores on a system: $NUM_CORES"
           if [ "$NUM_CORES" -gt 4 ]
           then
               NUM_THREADS=$(($NUM_CORES / 4))
               NUM_THREADS=-j$NUM_THREADS
           fi
    else
        NUM_CORES=""
    fi
    }

**Comment by vsureshkumarp** [comment]
Few instances observed a couple of hang issues especially when VM used as server for build procedure. Sometimes aggressive compilation causes random memory or other issues especially on VMs. Added additional check not to use all the cores available in physical server/VM which can avoid the aggressive parallel compilation.  It is just to minimize resources required for build procedures and to make sure scripts work for both physical and VM environments.

**Comment by asafravid** [comment]
Thanks for the details @vsureshkumarp 

 1. If you would be so kind as to add the above (formalized) as a comment for `get_num_cores()` that would be much appreciated.
 2. Can you add logic in which if these `NUM_CORES` and/or `NUM_THREADS` are already set in environment (`export` etc) then they shall be used explicitly by the script(s)?

**Comment by jfingerh** [comment]
One thing that might be happening with large numbers of parallel jobs is that they can consume a lot of RAM, and if you run out of RAM and swap, Linux has an OOM process killer that starts killing processes that consume significant memory.  You want to stay away from that.  Guaranteeing you stay away from that is not so simple to calculate in a script, though, except by being conservative in amount of make parallelism used.

**Comment by mestery** [comment]
> Thanks for the details @vsureshkumarp
> 
> 1. If you would be so kind as to add the above (formalized) as a comment for `get_num_cores()` that would be much appreciated.
> 2. Can you add logic in which if these `NUM_CORES` and/or `NUM_THREADS` are already set in environment (`export` etc) then they shall be used explicitly by the script(s)?

It would be easy to check if NUM_CORES and NUM_THREADS are already set and skip overriding them, I'll push a PR to do this. I'll also add a comment.
