### ISSUE TITLE
Build of Ubuntu 20.04 container fails

### ISSUE THREAD

**Issue by PatrickKutch** [ipdk-io/ipdk#283]
Setup proxy in config file. 
ran: ipdk install ubuntu2004
then: ipdk build --no-cache --use-proxy 

After a while, the following error occurs:
ERROR: Could not detect Ninja v1.8.2 or newer

A full log can be found at /root/p4-sde/p4-driver/src/lld/dpdk/dpdk_src/build/meson-logs/meson-log.txt
make[4]: *** [Makefile:480: all] Error 1
make[4]: Leaving directory '/root/p4-sde/p4-driver/src/lld/dpdk'
make[3]: Leaving directory '/root/p4-sde/p4-driver/src'
make[3]: *** [Makefile:2812: all-recursive] Error 1
make[2]: *** [Makefile:1095: all] Error 2
make[2]: Leaving directory '/root/p4-sde/p4-driver/src'
make[1]: Leaving directory '/root/p4-sde/p4-driver'
make[1]: *** [Makefile:526: all-recursive] Error 1

Fedora container built fine

**Comment by vsureshkumarp** [comment]
Freshly downloaded IPDK and tried to build Docker Ubuntu 20.04. It went well without any issues.

root@user:~/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build/scripts# ipdk build --no-cache --use-proxy
Loaded /root/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build/scripts/ipdk_default.env
Loaded /root/.ipdk/ipdk.env
~/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build ~/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build/scripts
Use docker buildx build!
~/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build/networking ~/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build ~/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build/scripts
[+] Building 1493.8s (24/24) FINISHED                                                                                              
 => [internal] load build definition from Dockerfile.ubuntu                                                                   0.0s
 => => transferring dockerfile: 1.78kB                                                                                        0.0s
 => [internal] load .dockerignore                                                                                             0.0s
 => => transferring context: 2B                                                                                               0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                               0.0s
 => [internal] load build context                                                                                             0.3s
 => => transferring context: 49.29kB                                                                                          0.3s
 => CACHED [base 1/9] FROM docker.io/library/ubuntu:20.04                                                                     0.0s
 => [base 2/9] RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections                             0.6s
 => [base 3/9] WORKDIR /root                                                                                                  0.0s
 => [base 4/9] COPY ./scripts scripts                                                                                         0.0s
 => [base 5/9] COPY ./examples /root/examples                                                                                 0.0s
 => [base 6/9] COPY ./start_p4ovs.sh /root/start_p4ovs.sh                                                                     0.0s
 => [base 7/9] COPY ./run_ovs_cmds /root/run_ovs_cmds                                                                         0.0s
 => [base 8/9] COPY ./patches /root/patches                                                                                   0.0s
 => [base 9/9] RUN /root/scripts/distro_pkg_install.sh -b &&     /root/start_p4ovs.sh /root &&     /root/scripts/run_clea  1385.9s
 => [p4-ovs-container  2/11] COPY --from=base /root/scripts /root/scripts                                                     0.0s 
 => [p4-ovs-container  3/11] COPY --from=base /root/examples /root/examples                                                   0.0s 
 => [p4-ovs-container  4/11] COPY --from=base /root/p4c /root/p4c                                                             0.2s 
 => [p4-ovs-container  5/11] COPY --from=base /root/p4-sde/install /root/p4-sde/install                                       2.2s 
 => [p4-ovs-container  6/11] COPY --from=base /root/p4ovs /root/p4ovs                                                         2.0s 
 => [p4-ovs-container  7/11] COPY --from=base /root/source_code /root/source_code                                             0.0s 
 => [p4-ovs-container  8/11] COPY --from=base /root/configs/tofino_skip_p4_no_bsp.conf      /usr/share/stratum/target_skip_p  0.0s
 => [p4-ovs-container  9/11] COPY --from=base /root/configs/dpdk_port_config.pb.txt /usr/share/stratum/dpdk_port_config.pb.t  0.0s
 => [p4-ovs-container 10/11] COPY --from=base /root/p4-sde/install/share/target_sys/zlog-cfg /usr/share/target_sys/zlog-cfg   0.0s
 => [p4-ovs-container 11/11] RUN if [ "NO" = "YES" ]; then         /root/scripts/distro_pkg_install.sh -d;     else          89.1s
 => exporting to image                                                                                                       11.4s
 => => exporting layers                                                                                                      11.4s
 => => writing image sha256:3b7dee82060bac95fa5dcb3cdd9c7a249b4915d3f802fd1f38e1a518bc46c5d2                                  0.0s 
 => => naming to ghcr.io/ipdk-io/ipdk-ubuntu2004-x86_64:sha-3264e7d                                                           0.0s 
~/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build ~/pv/IPDK-ISSUES/UBUNTU-ISSUES/ipdk/build/scripts 


root@user:~/pv/MEV-TS-DOCKER-IMAGES# docker images
REPOSITORY                                                   TAG                   IMAGE ID       CREATED         SIZE
ghcr.io/ipdk-io/ipdk-ubuntu2004-x86_64                       sha-3264e7d           3b7dee82060b   6 minutes ago   2.01GB

**Comment by PatrickKutch** [comment]
I did a git pull (got lots of updates) and it works now.  Something changed between Saturday and today.

**Comment by vsureshkumarp** [comment]
No. No updates to network recipes for a couple of weeks.
@PatrickKutch - Can I close the issue as no issues are observed in image build?

**Comment by PatrickKutch** [comment]
Sure.  Though it is a bit concerning that it failed in the 1st place.

**Comment by vsureshkumarp** [comment]
@PatrickKutch - Tried Ubuntu 20.04 build multiple times to reproduce the issue. I haven't observed any build issues and every time succeeded without any issue.  Please reopen the issue if you observe it again.
