### ISSUE TITLE
Build of Ubuntu 18.04 container fails

### ISSUE THREAD

**Issue by PatrickKutch** [ipdk-io/ipdk#284]
Setup proxy in config file.
ran: ipdk install ubuntu1804
then: ipdk build --no-cache --use-proxy

Errored out after a while:

Successfully installed pip-21.3.1
Collecting grpcio
  Downloading grpcio-1.48.2-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from grpcio) (1.11.0)
Installing collected packages: grpcio
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Successfully installed grpcio-1.48.2
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f0dsnyt0/ovspy_7384b2183870492abca21ff9cda021ea/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f0dsnyt0/ovspy_7384b2183870492abca21ff9cda021ea/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mz_v88la
       cwd: /tmp/pip-install-f0dsnyt0/ovspy_7384b2183870492abca21ff9cda021ea/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-f0dsnyt0/ovspy_7384b2183870492abca21ff9cda021ea/setup.py", line 9, in <module>
      long_description=open('README.md').read(),
    File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 57: ordinal not in range(128)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3e/0c/34a7a123526bcd205a61996302fd7eb2b496572818d05a6e09772b640b94/ovspy-0.1.0b2.tar.gz#sha256=38a01de9ab122973af2c9e9b7eea70c9bf74bbb118951da14f0c25b3ceda4017 (from https://pypi.org/simple/ovspy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f0dsnyt0/ovspy_e576f7d372d54847a548f4d8d6cb9a86/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f0dsnyt0/ovspy_e576f7d372d54847a548f4d8d6cb9a86/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rtgy0wuy
       cwd: /tmp/pip-install-f0dsnyt0/ovspy_e576f7d372d54847a548f4d8d6cb9a86/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-f0dsnyt0/ovspy_e576f7d372d54847a548f4d8d6cb9a86/setup.py", line 9, in <module>
      long_description=open('README.md').read(),
    File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 57: ordinal not in range(128)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d5/07/e53edfc1411dc8d10525aee1f9bf8a911ae1fb8c9e2ab20493553d0d09a2/ovspy-0.1.0b1.tar.gz#sha256=872000c8a2e699d1f9403e0a1252bf58f81301445d6e1032ad7fd277b0e3159c (from https://pypi.org/simple/ovspy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement protobuf==3.20.1 (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0, 3.5.0.post1, 3.5.1, 3.5.2, 3.5.2.post1, 3.6.0, 3.6.1, 3.7.0rc2, 3.7.0rc3, 3.7.0, 3.7.1, 3.8.0rc1, 3.8.0, 3.9.0rc1, 3.9.0, 3.9.1, 3.9.2, 3.10.0rc1, 3.10.0, 3.11.0rc1, 3.11.0rc2, 3.11.0, 3.11.1, 3.11.2, 3.11.3, 3.12.0rc1, 3.12.0rc2, 3.12.0, 3.12.1, 3.12.2, 3.12.4, 3.13.0rc3, 3.13.0, 3.14.0rc1, 3.14.0rc2, 3.14.0rc3, 3.14.0, 3.15.0rc1, 3.15.0rc2, 3.15.0, 3.15.1, 3.15.2, 3.15.3, 3.15.4, 3.15.5, 3.15.6, 3.15.7, 3.15.8, 3.16.0rc1, 3.16.0rc2, 3.16.0, 3.17.0rc1, 3.17.0rc2, 3.17.0, 3.17.1, 3.17.2, 3.17.3, 3.18.0rc1, 3.18.0rc2, 3.18.0, 3.18.1, 3.18.3, 3.19.0rc1, 3.19.0rc2, 3.19.0, 3.19.1, 3.19.2, 3.19.3, 3.19.4, 3.19.5, 3.19.6, 4.0.0rc1, 4.0.0rc2, 4.21.0rc1, 4.21.0rc2, 4.21.0)
ERROR: No matching distribution found for protobuf==3.20.1
The command '/bin/bash -c /root/scripts/distro_pkg_install.sh -b &&     /root/start_p4ovs.sh /root &&     /root/scripts/run_cleanup.sh /root ${KEEP_SOURCE_CODE} ${DEPLOYMENT_IMAGE}' returned a non-zero code: 1

**Comment by nupuruttarwar** [comment]
Hello Patrick, Ubuntu 18.04 is not officially supported version for ipdk container(https://github.com/ipdk-io/ipdk/blob/main/RELEASENOTES.md) as officially Ubuntu Linux 18.04 is supported only till end of April 2023.
Supported versions are Ubuntu 20.04 and Fedora 33 for ipdk container. 

If you are interested in Ubuntu18.04 ipdk container, please look at the PR  https://github.com/ipdk-io/ipdk/pull/224 to resolve protobuf related build issues.

**Comment by PatrickKutch** [comment]
I'm not really interested, but it is listed as something that should work.  I'd ask that the documentation be updated with this information and a link to the method to resolve.

**Comment by vsureshkumarp** [comment]
Addressed Ubuntu 18.04 build issues with PR #293 
Please pull the latest code and use it for building Ubuntu 18.04 image.
