### ISSUE TITLE
qcow VM more elaborated instructions 

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#30]
In the informative readme, (so as to make it more informative / efficient) Can you please provide a link (or better yet, add your step by step instructions) demonstrating how to run  a qcow vm and which image you used? I’m having trouble running / logging into the VM using ssh so searching for a simpler way and/or something to save time here and concentrate on the ovs traffic part

Much appreciated

**Comment by asafravid** [comment]
I managed, at last
I suggest you mention the `virt-manager` which simplifies (for instance along with http://archive.ubuntu.com/ubuntu/dists/bionic-updates/main/installer-amd64/20101020ubuntu543.19/images/netboot/) creation of a VM. And now one can continue with the Readme

I do see `qemu-kvm` instructions in the readme, so will try those as well

Closing issue

    qemu-kvm -smp 4 -m 1024M \
        -boot c -cpu host -enable-kvm -nographic \
        -L /root/pc-bios -name VM1_TAP_DEV \
        -hda ./vm1.qcow2 \
        -object memory-backend-file,id=mem,size=1024M,mem-path=/dev/hugepages,share=on \
        -mem-prealloc \
        -numa node,memdev=mem \
        -chardev socket,id=char1,path=/var/lib/docker/volumes/shared/_data/vhost-user-0 \
        -netdev type=vhost-user,id=netdev0,chardev=char1,vhostforce \
        -device virtio-net-pci,mac=00:e8:ca:11:aa:01,netdev=netdev0 \
        -serial telnet::6551,server,nowait &

**Comment by asafravid** [comment]
Can you please provide a link to a "Pre-built VM qcow2 image." per the readme instruction sin the traffic example section>

**Comment by asafravid** [comment]
I think this website _may_ help:
https://www.nongnu.org/pretest/downloads/

**Comment by asafravid** [comment]
I see `-name VM1_TAP_DEV` on both VM run commands -> is that a typo?

**Comment by asafravid** [comment]
Any Idea why the VMs stop after about 2 minutes?

    [root@PT-DT0647 ubuntu1604]# /usr/libexec/qemu-kvm -smp 4 -m 1024M     -boot c -cpu host -enable-kvm -nographic     -L /root/pc-bios -name VM1_TAP_DEV     -hda ./vm1.qcow2     -object memory-backend-file,id=mem,size=1024M,mem-path=/dev/hugepages,share=on     -mem-prealloc     -numa node,memdev=mem     -chardev socket,id=char1,path=/var/lib/docker/volumes/shared/_data/vhost-user-0     -netdev type=vhost-user,id=netdev0,chardev=char1,vhostforce     -device virtio-net-pci,mac=00:e8:ca:11:aa:01,netdev=netdev0     -serial telnet::6551,server,nowait &
    [3] 2955665
    [root@PT-DT0647 ubuntu1604]# /usr/libexec/qemu-kvm -smp 4 -m 1024M     -boot c -cpu host -enable-kvm -nographic     -L /root/pc-bios -name VM1_TAP_DEV     -hda ./vm2.qcow2     -object memory-backend-file,id=mem,size=1024M,mem-path=/dev/hugepages,share=on     -mem-prealloc     -numa node,memdev=mem     -chardev socket,id=char2,path=/var/lib/docker/volumes/shared/_data/vhost-user-1     -netdev type=vhost-user,id=netdev1,chardev=char2,vhostforce     -device virtio-net-pci,mac=00:e8:ca:11:bb:01,netdev=netdev1     -serial telnet::6552,server,nowait &
    [4] 2955671

    [3]+  Stopped                 /usr/libexec/qemu-kvm -smp 4 -m 1024M -boot c -cpu host -enable-kvm -nographic -L /root/pc-bios -name VM1_TAP_DEV -hda ./vm1.qcow2 -object memory-backend-file,id=mem,size=1024M,mem-path=/dev/hugepages,share=on -mem-prealloc -numa node,memdev=mem -chardev socket,id=char1,path=/var/lib/docker/volumes/shared/_data/vhost-user-0 -netdev type=vhost-user,id=netdev0,chardev=char1,vhostforce -device virtio-net-pci,mac=00:e8:ca:11:aa:01,netdev=netdev0 -serial telnet::6551,server,nowait
    [root@PT-DT0647 ubuntu1604]#
    
    [4]+  Stopped                 /usr/libexec/qemu-kvm -smp 4 -m 1024M -boot c -cpu host -enable-kvm -nographic -L /root/pc-bios -name VM1_TAP_DEV -hda ./vm2.qcow2 -object memory-backend-file,id=mem,size=1024M,mem-path=/dev/hugepages,share=on -mem-prealloc -numa node,memdev=mem -chardev socket,id=char2,path=/var/lib/docker/volumes/shared/_data/vhost-user-1 -netdev type=vhost-user,id=netdev1,chardev=char2,vhostforce -device virtio-net-pci,mac=00:e8:ca:11:bb:01,netdev=netdev1 -serial telnet::6552,server,nowait
    [root@PT-DT0647 ubuntu1604]#
    [root@PT-DT0647 ubuntu1604]#

**Comment by stolsma** [comment]
I had also problems getting more then one vm running and I just found out that it is related to the Hugepage setting in the qemu-kvm startup command. The readme is stating tu use `mem-path=/dev/hugepages` but the hugepage script is defining `/mnt/huge` 😢 When I changed it to `mem-path=/mnt/huge` everything worked as expected and now my VM's stay running.....

Hope this helps you too?? If so this need to be changed in the readme....

**Comment by mestery** [comment]
Take a look [here](https://github.com/ipdk-io/ipdk/blob/main/build/IPDK_Container/scripts/rundemo.sh#L33-L38) for how I'm able to pull down some Xenial images. There is logic in there to enable a cloud-init ISO as well, which makes it nice.
