### ISSUE TITLE
On certain rootfs the /etc/resolv.conf has the default (ubuntu image pull) nameserver 8.8.8.8 instead of required one and requires a workaround

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#39]
Due to some restrictions on the `rootfs` (using the thin provisioning storage), the `/etc/resolv.conf` is unchangeable (I think due to certain rottfs restrictions)

Hence, my workaround (which works well, but I suppose a cleaner way should be committed):

`RUN echo "nameserver 10.5.102.111" >> /etc/resolv.conf && cat /etc/resolv.conf && apt-get update`
For each `RUN` command as each `RUN` command runs in its own container rendering any change in `/etc/resolv.conf` irrelevant for the following `RUN` command (within `Dockerfile`)

Suggestions (apart from my workaround above)?

How about running the whole thing in a single `RUN` command? Or making the `/etc/resolv.conf` stateful (meaning it remains the same after being changed, during the following `RUN` command within the `Dockerfile`)?

**Comment by stolsma** [comment]
Do you mean at container creation time or at container runtime?

I never encountered dns problems at container creation time, so I can't help you with that.

For container runtime the current scripts use the default docker network and then docker overwrites `resolv.conf` with the `resolv.conf` file of the host system at ipdk container startup. See https://docs.docker.com/config/containers/container-networking/#dns-services

By adding `--dns=x.x.x.x` to the ipdk container startup line you can override this only for default docker networks.  If you use custom docker networks you need to run a script in the container at startup of the container to set the correct `resolv.conf` contents, `--dns=` won't work there.

**Comment by asafravid** [comment]
Closing as not a blocker and target-dependent
