### ISSUE TITLE
Preventing the ipdk container from exiting upon each error in the bash

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#40]
It is frustrating (big big overhead on slow storage) that every error in bash command line (for instance the below wrong command) makes the container exit.

    root@f1b5dceeb02b:/p4-sde# cat /root/
    cat: /root/: Is a directory

    Makefile:57: recipe for target 'volume' failed
    make: *** [volume] Error 1
    root@node1:

How can this be prevented?

Can you add `-dit` instead of `-it` in the `Makefile`?

    ## Create a volume and then configure the container to use it.
    volume: ;docker volume create shared; docker run --rm --cap-add ALL --privileged -v shared:/tmp -dit ${IMAGE_NAME}:${TAG}

Other suggestions are **more** than welcome

Additional questions and an important request:
1. What is the difference between `make volume` and `make run`?
2. What is the difference between `make build` and `make build-nc`? Maybe cache _is_ preferred? I see that using `make build` uses previous fetches so looks like a very efficient way to run after some `bash` failure -> **Please** add this important information in the `Readme` (could have saved me hours and hours of work had I known about it. I digged in the `Makefile` and found out about it only just now)

        2) i) Run - 'make build-nc' - To build a docker image while no proxy.
           ii) Run - 'make build-nc-proxy' - To build a docker image while running
               behind proxy.
           iii) Run - 'make build' - To build a docker image while no proxy, **with cached previous build's data.** so as to save valuable re-run time.

**Comment by stolsma** [comment]
See #38 for some examples to run the container as docker daemon and connect with seperate connection... I will add extensive documentation for it in the next days....

**Comment by asafravid** [comment]
Thanks @stolsma I added a question in #38

**Comment by n-sandeep** [comment]
Hello @asafravid 

With the given steps in **README** and **run_ovs_cmds** we don't see this issue happening. You see such error when **errexit** is set in shell options ($SHELLOPTS).
Have you added any new script for your development? If yes, have you used **set -e** option in those scripts and did this option follow by an **set +e** before exiting the script?

Here is the quick UT performed once a fresh container is spawned:

root@ipdk:IPDK_Container# make volume
docker volume create shared; docker run --rm --cap-add ALL --privileged -v shared:/tmp -it ipdk/p4-ovs-fc33:e92d90f
shared
[root@866eac71e232 ~]#
[root@866eac71e232 ~]# cat /root/
cat: /root/: Is a directory
[root@866eac71e232 ~]# echo $SHELLOPTS
braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
[root@866eac71e232 ~]# cd scripts/
[root@866eac71e232 scripts]# source p4ovs_env_setup.sh /root/p4-sde/install
OS and Version details...
Fedora : 33


Updated Environment Variables ...
SDE_INSTALL: /root/p4-sde/install
PKG_CONFIG_PATH: /root/p4-sde/install/lib64/pkgconfig
LIBRARY_PATH:
LD_LIBRARY_PATH: :/root/p4-sde/install/lib:/root/p4-sde/install/lib64:/root/p4-sde/install/lib64:/usr/local/lib:/usr/local/lib64
PATH: /root/.local/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
C_INCLUDE_PATH:
CPLUS_INCLUDE_PATH:

[root@866eac71e232 scripts]# ./set_hugepages.sh
1024
1024
1024
[root@866eac71e232 scripts]# echo $SHELLOPTS
braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
[root@866eac71e232 scripts]# ./run_ovs.sh
Killing OVS Processes If Already Running....
Creating /var/run/openvswitch
.
.
.
2022-01-03T21:14:44Z|00005|reconnect|INFO|unix:/usr/local/var/run/openvswitch/db.sock: connecting...
2022-01-03T21:14:44Z|00006|reconnect|INFO|unix:/usr/local/var/run/openvswitch/db.sock: connected
All Processes Started.....
[root@866eac71e232 scripts]# echo $SHELLOPTS
braceexpand:emacs:hashall:histexpand:history:interactive-comments:monitor
[root@866eac71e232 scripts]# cat /root/
cat: /root/: Is a directory
[root@866eac71e232 scripts]#

**Comment by n-sandeep** [comment]
Hello @asafravid

What is the difference between make volume and make run?
  > make run command works similar to "docker run"
  > make volume command also creates a shared directory between container & host machine and then runs a container similar to docker run.

Regarding document change for "make build" to retain proxy, we will raise a review along with one more fix we are targeting.

Closing this pull request, as steps mentioned in README doesnt cause any container exit.
