### ISSUE TITLE
make volume fails after successful make build-nc

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#41]
This is a frustrating error: 
After a long and successful run of the `make build-nc`, the `make volume` fails:

    Step 14/18 : COPY ./start_p4ovs.sh /root/start_p4ovs_stage1.sh
     ---> fa5667d28322
    Step 15/18 : COPY ./start_p4ovs.sh /root/start_p4ovs_stage2.sh
     ---> ea7d954f5ddb
    Step 16/18 : COPY ./start_p4ovs.sh /root/start_p4ovs_stage3.sh
     ---> 86a5213e3b8b
    Step 17/18 : COPY ./meson.build /root/meson.build
     ---> 5bff07c0f2f7
    Step 18/18 : COPY ./run_ovs_cmds /root/run_ovs_cmds
     ---> 2a832892f052
    Successfully built 2a832892f052
    Successfully tagged ipdk/p4-ovs-ubuntu20.04:ba2eda1
    root@kub-node1-smadarf:~/ipdk/build/IPDK_Container/Ubuntu20.04# make volume
    docker volume create shared; docker run --rm --cap-add ALL --privileged -v shared:/tmp -itd ipdk/p4-ovs-ubuntu20.04:ba2eda1
    shared
    Unable to find image 'ipdk/p4-ovs-ubuntu20.04:ba2eda1' locally
    docker: Error response from daemon: pull access denied for ipdk/p4-ovs-ubuntu20.04, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
    See 'docker run --help'.
    Makefile:57: recipe for target 'volume' failed
    make: *** [volume] Error 125

What could this be caused by?

**Comment by asafravid** [comment]
Trying `docker system prune` in the meanwhile

**Comment by vsureshkumarp** [comment]
Looks like image "ipdk/p4-ovs-ubuntu20.04:ba2eda1" got removed from your local system.

This kind of issue observed only when 
          - Somehow image build failed (Not the case with your scenario)
          - Images removed explicitly from the local system 

The command **_docker system prune_** clean up the all or selected images and this might have caused the above error.
Please run **_docker images_** and check whether image build with as part of _**make build-nc**_ is available or not.

**Comment by asafravid** [comment]
@vsureshkumarp but I issued the docker system prune **after** this error...

**Comment by vsureshkumarp** [comment]
@asafravid,  Are you still facing the same issue even after images are available locally on your system?
If yes, can you please paste o/p the command **_docker images_** when you see the above error?
We tried to reproduce the issue and it didn't happen even single occurrence when required images are available.
Same issue is happening when we remove the images from the local system.

**Comment by asafravid** [comment]
I switched to another machine and this is not occuring thus far
I'm closing temporarily and shall re-open if required
