### ISSUE TITLE
Some systems require more sudo apt-get install packages for build_p4c to run successfully

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#42]
build_p4c () {
        chmod +x ${SCRIPTS_DIR}/build_p4c.sh && \
            ${SHELL_STRING} ${SCRIPTS_DIR}/build_p4c.sh "$WORKDIR"
    }

Within it `cmake -DENABLE_BMV2=OFF -DENABLE_EBPF=OFF -DENABLE -DENABLE_P4C_GRAPHS=OFF -DENABLE_P4TEST=OFF -DENABLE_GTESTS=OFF ..` may fail if `FLEX_EXECUTABLE` is missing:

    CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
      Could NOT find FLEX (missing: FLEX_EXECUTABLE) (Required is at least
      version "2.0")
    Call Stack (most recent call first):
      /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
      /usr/share/cmake-3.16/Modules/FindFLEX.cmake:220 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
      CMakeLists.txt:104 (find_package)

Solution, have `sudo apt-get install flex` be called prior (or earlier in `Dockerfile`)

**Comment by stolsma** [comment]
You're taking about the Ubuntu container setup script that is missing this?

Please add enough 'environment ' information to understand the problem when opening a issue. Else it is really difficult for other people to help tackle the problem.

**Comment by asafravid** [comment]
@stolsma indeed this is the Ubuntu20.04 (build no then make volume) within the repository

**Comment by asafravid** [comment]
Closing, `flex libfl-dev` exists in `Dockerfile`
Will re-open if issue re-occurs
