### ISSUE TITLE
VM crash when following instructions

### ISSUE THREAD

**Issue by mestery** [ipdk-io/ipdk#46]
When following the README instructions as written, I can't get two VMS to run. Note that I'm not running OVS inside a container, but instead natively in a Vagrant VM with nested virtualization enabled (inside of Virtualbox). [This line](https://github.com/ipdk-io/ipdk/blob/main/build/IPDK_Container/README#L124) indicates to pass /dev/hugepages to the first VM. However, [this line](https://github.com/ipdk-io/ipdk/blob/main/build/IPDK_Container/README#L138) then says to pass the same file to the second VM. When I do this, the first VM takes a kernel fault and crashes. If I give each VM a separate file (say, for example `/hugetlbfs1` and `/hugetlbfs2`, then the VMs work ok.

Note that even with them running, I don't see traffic passing and it's not clear to me how to debug this. This is how I stumbled onto #45 in fact.

**Comment by mestery** [comment]
@vsureshkumarp Wondering if you might have an idea about this one? @Namrata-intel mentioned I should ping you for any comments. Thanks!

**Comment by stolsma** [comment]
I had the same problem! I solved it by using /mnt/huge for both VM's. The hugetlb script mounts /mnt/huge so that should be the problem I think...

**Comment by mestery** [comment]
This was exactly the issue, and now it works! I've updated my script and such in #37 to reflect this.
