### ISSUE TITLE
"terminate called after throwing an instance of 'bfrt::(anonymous namespace)::fileOpenFailException'" upon invocation of "/root/scripts/run_ovs.sh"

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#53]
Upon invocation of root@df5632ec08ff:~/scripts# /root/scripts/run_ovs.sh

I get and error: `BF_BFRT FATAL - Unable to find any BfRt Json File`

    root@df5632ec08ff:~/scripts# /root/scripts/run_ovs.sh
    Killing OVS Processes If Already Running....
    Killing ovsdb-server process....
    Creating /var/run/openvswitch
    Starting OvS DB server....
    Staring OvS VSWITCHD Process....
    2022-01-10T20:54:07Z|00001|vlog|INFO|opened log file /tmp/ovs-vswitchd.log
    2022-01-10T20:54:07Z|00002|ovs_numa|INFO|Discovered 24 CPU cores on NUMA node 0
    2022-01-10T20:54:07Z|00003|ovs_numa|INFO|Discovered 1 NUMA nodes and 24 CPU cores
    WARNING: Logging before InitGoogleLogging() is written to STDERR
    I20220110 20:54:07.516815 18364 bf_sde_wrapper.cc:1530] bf_sysfs_fname: /sys/class/bf/bf0/device/dev_add
    Install dir: /usr (0xaaaaba385a70)
    bf_switchd: system services initialized
    bf_switchd: loading conf_file /usr/share/stratum/target_skip_p4_no_bsp.conf...
    bf_switchd: processing device configuration...
    Configuration for dev_id 0
      Family        : dpdk
    bf_switchd: processing P4 configuration...
    P4 profile for dev_id 0
    P4 EAL args dummy -n 4 -c 3
    num P4 programs 1
      p4_name: dummy
      bfrt_config:
      port_config:
      p4_pipeline_name: pipe
        context:
        config:
      Pipes in scope [0 1 2 3 ]
      diag:
      accton diag:
      non_default_port_ppgs: 0
      SAI default initialize: 1
    Operational mode set to DPDK MODEL
    Initialized the device types using PAL handler registration
    bf_switchd: drivers initialized
    Skipping P4 program load for dev_id 0
    EAL: Detected CPU lcores: 24
    EAL: Detected NUMA nodes: 1
    EAL: Detected shared linkage of DPDK
    EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
    EAL: Selected IOVA mode 'VA'
    EAL: No available 16777216 kB hugepages reported
    EAL: 1024 hugepages of size 2097152 reserved, but no mounted hugetlbfs found for that size
    EAL: VFIO support initialized
    TELEMETRY: No legacy callbacks, legacy socket not created
    2022-01-10 20:54:08.064048 BF_BFRT FATAL - Unable to find any BfRt Json File
    terminate called after throwing an instance of 'bfrt::(anonymous namespace)::fileOpenFailException'
    terminate called recursively
    2022-01-10T20:54:09Z|00002|daemon_unix|ERR|fork child died before signaling startup (killed (Aborted), core dumped)
    ovs-vswitchd: could not detach from foreground session
    root@df5632ec08ff:~/scripts#

Any ideas how to approach/fix this?

Environment is arm64 (`aarch64`)

**Comment by mestery** [comment]
Someone must have broken the P4 code upstream, because I'm seeing this on x86_64 as well:

```
TELEMETRY: No legacy callbacks, legacy socket not created
2022-01-10 21:10:34.605317 BF_BFRT FATAL - Unable to find any BfRt Json File
2022-01-10 21:10:34.605488 BF_BFRT ERROR - makeBfRtInfo:383 Failed to create BfRtInfo for dev_id  0
```

**Comment by mestery** [comment]
I found the case, it was my `set_hugepages.sh` fix from [this](https://github.com/ipdk-io/ipdk/commit/1a363fde066908a6916112a98c77fe144099a89b) commit. I'll push a revert now.

**Comment by mestery** [comment]
Per @Namrata-intel, this error is benign, I can confirm I see this error even when things work.

**Comment by asafravid** [comment]
Looks like indeed a benign error:

    root@df5632ec08ff:~# nano scripts/get_p4ovs_repo.sh
    root@df5632ec08ff:~# ps -ef | grep ovs
    root     18361     1  0 Jan10 ?        00:00:00 ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile --detach
    root     18383     1  0 00:07 pts/0    00:00:00 grep --color=auto ovs
    root@df5632ec08ff:~#

Looks like ovs running in arm64 at last

I you can confirm @mestery I will close this issue

**Comment by mestery** [comment]
Yup, it's benign. Also, it's a duplicate of #8. So closing it should be ok. Appears the fix needs to be done upstream in Stratum.

**Comment by stolsma** [comment]
No fix needed upstream as this is expected behavior when starting the control part. In recent Stratum code this error is decremented to info level.

**Comment by asafravid** [comment]
@mestery @stolsma

Reopening this issue since it seems that the issue is not related to `"BF_BFRT FATAL - Unable to find any BfRt Json File"` (renamed subject)

It seems that the `ovs-vswitchd` terminated due to `terminate called after throwing an instance of 'bfrt::(anonymous namespace)::fileOpenFailException'`

What could be the reason for that? Which file caused it?

**Comment by stolsma** [comment]
Is this on the arm system?

**Comment by asafravid** [comment]
@stolsma yes

**Comment by asafravid** [comment]
Any more information which can be obtained from `ovs-vswitchd.log` (such as verbosity increase)?

    root@9cbe3c2e74af:~/scripts# cat /tmp/ovs-vswitchd.log
    2022-01-12T09:02:09.922Z|00001|vlog|INFO|opened log file /tmp/ovs-vswitchd.log
    2022-01-12T09:02:09.928Z|00002|ovs_numa|INFO|Discovered 24 CPU cores on NUMA node 0
    2022-01-12T09:02:09.928Z|00003|ovs_numa|INFO|Discovered 1 NUMA nodes and 24 CPU cores
    2022-01-12T09:02:10.281Z|00002|daemon_unix|ERR|fork child died before signaling startup (killed (Aborted), core dumped)
    2022-01-12T09:02:10.281Z|00003|daemon_unix|EMER|could not detach from foreground session
    root@9cbe3c2e74af:~/scripts#

**Comment by asafravid** [comment]
@mestery @stolsma Might this be related?

From https://github.com/p4lang/p4-dpdk-target :

    P4 Compiler DPDK Backend:
            (https://github.com/p4lang/p4c/tree/main/backends/dpdk)
            P4C DPDK backend creates the artifact files used by p4-dpdk-target 
            and DPDK SWX pipeline.
            p4-dpdk-target uses bfrt.json to define the program independent frontend 
            bf_rt interface.
            context.json is used to map the P4 runtime info to the P4 DPDK target
            specific info.
            The P4 DPDK spec file from P4C DPDK, which is used by DPDK SWX pipeline
            to setup the software pipeline, is also loaded through p4-dpdk-target.

So maybe a missing step?

**Comment by asafravid** [comment]
With @n-sandeep’s awesome help ovs-vswitchd now up and running on `arm64`:

@mestery Thanks for updating stratum, I'll try without my patches once you bump it up however probably unrelated directly to the stratum hash (commit) position

    ...
    All Processes Started.....
    root@9cbe3c2e74af:~/scripts# ps -ef | grep ovs
    root     10070     1  0 21:44 ?        00:00:00 ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile --detach
    root     10073     1 99 21:44 ?        00:00:33 ovs-vswitchd --pidfile --detach --no-chdir --mlockall --log-file=/tmp/ovs-vswitchd.log --verbose
    root     10095     1  0 21:45 pts/0    00:00:00 grep --color=auto ovs
    root@9cbe3c2e74af:~/scripts#

All relevant changes in https://github.com/asafravid/ipdk for now

Much appreciated!

Closing issue.

Summary:
Relevant changes here https://github.com/asafravid/p4-dpdk-target/commits/main/src/bf_rt/bf_rt_common/bf_rt_info_impl.cpp
