### ISSUE TITLE
"sudo gnmi-cli set "device:..." step fails in Section 2

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#54]
From within the container (ovsdb server running well), The following step in the readme (stage 2 

    ~/scripts# sudo gnmi-cli set "device:virtual-device,name:net_vhhost0,host:host1,\
           device-type:VIRTIO_NET,queues:1,socket-path:/tmp/vhost-user-0,\
           port-type:LINK"
    Return grpc errno (14), Reason: failed to connect to all addresses
    root@82a4bd994e76:~/scripts#

What am I missing?

Sectio 2 steps:

    root@82a4bd994e76:~/scripts# ps -ef | grep ovs
    root        27     1  0 18:58 ?        00:00:00 ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile --detach
    root        43     1  0 19:00 pts/0    00:00:00 grep --color=auto ovs
    root@82a4bd994e76:~/scripts# rm -rf /tmp/vhost-user-*
    t/p4-sde/install6:~/scripts# cd /root/scripts/ && source p4ovs_env_setup.sh /root
    OS and Version details...
    Ubuntu : 20.04
    
    
    Updated Environment Variables ...
    SDE_INSTALL: /root/p4-sde/install
    PKG_CONFIG_PATH: /root/p4-sde/install/lib/aarch64-linux-gnu/pkgconfig
    LIBRARY_PATH:
    LD_LIBRARY_PATH: :/root/p4-sde/install/lib:/root/p4-sde/install/lib64:/root/p4-sde/install/lib/aarch64-linux-gnu:/usr/local/lib:/usr/local/lib64:/root/p4-sde/install/lib:/root/p4-sde/install/lib64:/root/p4-sde/install/lib/aarch64-linux-gnu:/usr/local/lib:/usr/local/lib64
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    C_INCLUDE_PATH:
    CPLUS_INCLUDE_PATH:
    
    RY_PATH="$LD_LIBRARY_PATH"'# alias sudo='sudo PATH="$PATH" HOME="$HOME" LD_LIBRAR
    host0,host:host1,\~/scripts# sudo gnmi-cli set "device:virtual-device,name:net_vh
    >        device-type:VIRTIO_NET,queues:1,socket-path:/tmp/vhost-user-0,\
    >        port-type:LINK"
    
    Return grpc errno (14), Reason: failed to connect to all addresses
    root@82a4bd994e76:~/scripts#
    host0,host:host1,\~/scripts# sudo gnmi-cli set "device:virtual-device,name:net_vh
           device-type:VIRTIO_NET,queues:1,socket-path:/tmp/vhost-user-0,\
           port-type:LINK"
    Return grpc errno (14), Reason: failed to connect to all addresses
    root@82a4bd994e76:~/scripts#

**Comment by stolsma** [comment]
What is `ps -ef | grep ovs` showing?? Looks like `ovs-vswitchd` is not running....
