### ISSUE TITLE
vagrant instructions missing from readme.md

### ISSUE THREAD

**Issue by jbrandeb** [ipdk-io/ipdk#57]
I think the root directory [readme.md](https://github.com/ipdk-io/ipdk/blob/main/build/IPDK_Container/README.md) should reference the method, code and readme added in #37. Thoughts?

**Comment by mestery** [comment]
I tend to agree on that, as I think the Vagrant instructions are easier and less error prone. @jbrandeb you can submit a PR I'll review, or I can take a crack at rewording things tomorrow. I'd suggest moving the current `README.md` to something like `README_DOCKER.md` and then have a new `README.md` reference both vagrant and docker instructions.

**Comment by stolsma** [comment]
@mestery I'm already working on a docker demo and support script + a README for it in #38 . I have a first implementation there but still working on it. 

I also try to factor out script code that can be shared between the Vagrant, bare metal and Docker examples like for example the creation of the vm images, hugepages call, creation of new ports etc etc. But that could also be further worked on in next pull requests.

Please look at it and comment if I'm on the right way.

The generic README should reference the different running environments (Vagrant, bare metal and Docker) and link to the specific READMEs. It also should link to a more specific README with internal documentation about how todo low level setup things etc.

Just m2c

**Comment by mestery** [comment]
@stolsma I put some comments on your commit. Your's is a bit larger, we can iterate on yours or @jbrandeb can submit an initial smaller PR to address this one.

**Comment by stolsma** [comment]
@mestery @jbrandeb Agreed, lets start on the smaller one, I will iterate on that one in my pr...
