### ISSUE TITLE
Fedora log when chose ubuntu

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#70]
I cloned the latest head, and seeing fedora image pull instead of ubuntu

    ~/ipdk/build# ./ipdk install
    Loaded /root/ipdk/build/scripts/ipdk_default.env
    
    As last step execute:
      export PATH=/root/ipdk/build:$PATH
    to add the IPDK CLI to your path in the running environment!
    ~/ipdk/build# export PATH=/root/ipdk/build:$PATH
    ~/ipdk/build# BASE_IMG=ubuntu:20.04
    ~/ipdk/build# IMAGE_NAME=ipdk/p4-ovs-ubuntu20.04
    ~/ipdk/build# DOCKERFILE=${SCRIPT_DIR}/Dockerfile.ubuntu
    ~/ipdk/build# ipdk build --no-cache
    Loaded /root/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    ~/ipdk/build ~/ipdk/build
    Sending build context to Docker daemon  131.6kB
    Step 1/15 : ARG BASE_IMG=${BASE_IMG}
    Step 2/15 : FROM ${BASE_IMG} AS base
    33: Pulling from library/fedora
    c1323e24d83b: Extracting [============================================>      ]  55.15MB/61.52MB

Is this normal/ok? a typo? am I missing something?

**Comment by asafravid** [comment]
I think what's missing is making the `BASE_IMG=ubuntu:20.04, IMAGE_NAME=ipdk/p4-ovs-ubuntu20.04 and DOCKERFILE=${SCRIPT_DIR}/Dockerfile.ubuntu` my user CLI file
I'll fix and re-check
for now closing

**Comment by asafravid** [comment]
Reopening as even with `export` it still uses fedora, and unclear (from readme) as of where the user CLI configuration file should reside

    ~/ipdk# export BASE_IMG=ubuntu:20.04
    ~/ipdk# export IMAGE_NAME=ipdk/p4-ovs-ubuntu20.04
    ~/ipdk# export DOCKERFILE=${SCRIPT_DIR}/Dockerfile.ubuntu
    ~/ipdk# ipdk build --no-cache
    Loaded /root/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    ~/ipdk/build ~/ipdk
    Sending build context to Docker daemon  131.6kB
    Step 1/15 : ARG BASE_IMG=${BASE_IMG}
    Step 2/15 : FROM ${BASE_IMG} AS base
    33: Pulling from library/fedora
    c1323e24d83b: Downloading [========>                                          ]  10.75MB/61.52MB

What am I missing?

**Comment by asafravid** [comment]
I think file should be placed in `$HOME/.ipdk/ipdk.env` (however it is unclear from the readme unless I'm missing something)

     # add empty ipdk.env file if not already there
        if [ -f "$HOME/.ipdk/ipdk.env" ]; then
                echo "User changable IPDK configuration file is already defined at "
                echo "'~/.ipdk/ipdk.env'. Remove this file when new install is required!"
        else

I'll try it and update

**Comment by asafravid** [comment]
I see now in the logs:

    ~/ipdk/build# ipdk install
    Loaded /root/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    User changable IPDK configuration file is already defined at
    '~/.ipdk/ipdk.env'. Remove this file when new install is required!

Closing... will reopen (I think readme file should explicitly mention this file though)

**Comment by asafravid** [comment]
Updated `/root/.ipdk/ipdk.env` yet the instructions in readme have an error it seems:

    ~/ipdk/build# cat /root/.ipdk/ipdk.env
    #
    # IPDK CLI configuration file
    # See for more information https://github.com/ipdk-io/ipdk/blob/main/build/IPDK_Container/README_DOCKER.md#CLI- 
   configuration-settings
    #
    # /root/ipdk/build/scripts contains the location of the 'sourcing' ipdk script when read.
    #
    BASE_IMG=ubuntu:20.04
    IMAGE_NAME=ipdk/p4-ovs-ubuntu20.04
    DOCKERFILE=${SCRIPT_DIR}/Dockerfile.ubuntu
    ~/ipdk/build# ipdk build --no-cache
    Loaded /root/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    ~/ipdk/build ~/ipdk/build
    unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/ipdk/build/scripts/Dockerfile.ubuntu: no 
    such file or directory
    ~/ipdk/build
    ~/ipdk/build#

**Comment by asafravid** [comment]
Ok fixed

Please note: readme instructions instructing to use `DOCKERFILE=${SCRIPT_DIR}/Dockerfile.ubuntu` should be fixed to `DOCKERFILE=Dockerfile.ubuntu`

Leaving open until fixed (I'll try to make a quick pull request)

    ~/ipdk/build# ipdk build --no-cache
    Loaded /root/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    ~/ipdk/build ~/ipdk/build
    Sending build context to Docker daemon  131.6kB
    Step 1/18 : ARG BASE_IMG=${BASE_IMG}
    Step 2/18 : FROM ${BASE_IMG} AS base
    20.04: Pulling from library/ubuntu
    5f3d23ccb99f: Downloading [=====>

**Comment by asafravid** [comment]
Fixed in https://github.com/ipdk-io/ipdk/pull/71

**Comment by stolsma** [comment]
Did you execute `./ipdk install` ? If you did the file should have been installed in `~/.ipdk/ipdk.env`

At the moment I'm writing a extension to the install command to change to another base image: `ipdk install [container base image]` -> `ipdk install ubuntu:2004` This will make everything a lot easier...

**Comment by asafravid** [comment]
Yes I’ve used ipdk install prior
