### ISSUE TITLE
program not found or is not executable (-grpc_out: protoc-gen-grpc: Plugin failed with status code 1)

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#76]
I'm running latest `ipdk` head on CentOS 8, `Dockerfile.ubuntu` 

The following errors during `ipdk build --no-cache` prevnt ovs build:

    protoc -I./external/googleapis -I/usr/local/include -I./p4runtime/proto --grpc_out=./p4proto/p4rt/proto --plugin=protoc-gen- grpc=`which grpc_cpp_plugin` ./p4runtime/proto/p4/v1/p4runtime.proto
    : program not found or is not executable
    : program not found or is not executable
    --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
    --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
    make: *** [Makefile:9755: p4proto/p4rt/proto/p4/v1/p4runtime.grpc.pb.h] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [Makefile:9755: p4proto/p4rt/proto/p4/v1/p4runtime.grpc.pb.cc] Error 1
    protoc -I./external/googleapis -I/usr/local/include -I./p4runtime/proto --grpc_out=./p4proto/p4rt/proto --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ./p4runtime/proto/p4/v1/p4runtime.proto
    protoc -I./external/googleapis -I/usr/local/include -I./p4runtime/proto --grpc_out=./p4proto/p4rt/proto --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` ./p4runtime/proto/p4/v1/p4runtime.proto
    : program not found or is not executable
    : program not found or is not executable
    --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
    --grpc_out: protoc-gen-grpc: Plugin failed with status code 1.
    make: *** [Makefile:9755: p4proto/p4rt/proto/p4/v1/p4runtime.grpc.pb.h] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [Makefile:9755: p4proto/p4rt/proto/p4/v1/p4runtime.grpc.pb.cc] Error 1

Suggestions?

**Comment by asafravid** [comment]
There are also many preceeding errors, for instance:

    In file included from /usr/include/string.h:495,
                 from /usr/include/google/protobuf/stubs/port.h:38,
                 from /usr/include/google/protobuf/stubs/common.h:46,
                 from /root/P4C/build/control-plane/p4/config/v1/p4info.pb.h:9,
                 from /root/P4C/build/control-plane/p4/config/v1/p4info.pb.cc:4:
    In function 'void* memset(void*, int, size_t)',
        inlined from 'void p4::config::v1::Digest::SharedCtor()' at /root/P4C/build/control-plane/p4/config/v1/p4info.pb.cc:10548:11,
        inlined from 'p4::config::v1::Digest::Digest()' at /root/P4C/build/control-plane/p4/config/v1/p4info.pb.cc:10527:13,
        inlined from 'void protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::InitDefaultsDigest()' at /root/P4C/build/control-plane/p4/config/v1/p4info.pb.cc:10523:1:
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:71:33: warning: 'void* __builtin_memset(void*, int, long unsigned int)' offset [25, 32] from the object at 'p4::config::v1::_Digest_default_instance_' is out of the bounds of referenced subobject 'p4::config::v1::Digest::preamble_' with type 'p4::config::v1::Preamble*' at offset 16 [-Warray-bounds]
       71 |   return __builtin___memset_chk (__dest, __ch, __len, __bos0 (__dest));
          |          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In function 'void* memset(void*, int, size_t)',
        inlined from 'void p4::config::v1::DirectMeter::SharedCtor()' at /root/P4C/build/control-    plane/p4/config/v1/p4info.pb.cc:8763:11,
        inlined from 'p4::config::v1::DirectMeter::DirectMeter()' at /root/P4C/build/control-plane/p4/config/v1/p4info.pb.cc:8741:13,
        inlined from 'void protobuf_p4_2fconfig_2fv1_2fp4info_2eproto::InitDefaultsDirectMeter()' at /root/P4C/build/control-plane/p4/conf

**Comment by asafravid** [comment]
And this one as well:

    CMake Warning at backends/ebpf/CMakeLists.txt:164 (message):
  Missing the libbpf dependency, disabling kernel tests.  You can install
  libbpf by running './build_libbpf' in the /root/P4C/backends/ebpf/runtime
  folder.

**Comment by rst0git** [comment]
> --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` 

Have you tried to install `protobuf-compiler-grpc` and `python3-grpcio`?

**Comment by asafravid** [comment]
Results is that after `ipdk start -d` followed by `ipdk connect`, the `ovs` is not running:

    root@170c0c3a0823:~/scripts# ps -ef | grep ovs
    root         502     489  0 14:41 pts/1    00:00:00 grep --color=auto ovs
    root@170c0c3a0823:~/scripts#

**Comment by asafravid** [comment]
> Have you tried to install `protobuf-compiler-grpc` and `python3-grpcio`?

@rst0git I'll try, thanks

**Comment by nupuruttarwar** [comment]
Fix is merged and able to build successfully with ubuntu container now
