### ISSUE TITLE
When was ubuntu20.04 build and container demo last tested?

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#78]
It seems the build fails and ovs doesn't run
See https://github.com/ipdk-io/ipdk/issues/76

**Comment by mestery** [comment]
I tested it very recently, and it worked fine, but I'll test it again today and verify.

**Comment by asafravid** [comment]
Thanks @mestery

**Comment by mestery** [comment]
See #82, I'm hitting a GRPC issue after merging #81, which fixed another issue you reported

**Comment by asafravid** [comment]
@mestery without #81 all works well?

**Comment by mestery** [comment]
@asafravid No, #81 fixed some of the issues, but now I'm hitting what is documented by #82.

**Comment by mestery** [comment]
Using native mode instead of containers, I was able to get the build to work just fine. But, this was in an existing VM, I'll blow that one away and try with a fresh VM.

**Comment by nupuruttarwar** [comment]
Fix is merged and able to build successfully with ubuntu container now

**Comment by asafravid** [comment]
I Confirm as well, just took latest `ipdk` and ran `ubuntu20.04` -> success

    root@1d0d709ed2c1:~/scripts# ps -ef | grep ovs
    root          35       1  0 14:57 ?        00:00:00 ovsdb-server --remote=punix:/usr/local/var/run/openvswitch/db.sock --remote=db:Open_vSwitch,Open_vSwitch,manager_options --pidfile --detach
    root          39       1 99 14:57 ?        00:01:40 ovs-vswitchd --pidfile --detach --no-chdir --mlockall --log-file=/tmp/logs/ovs-vswitchd.log
    root          77      64  0 14:59 pts/1    00:00:00 grep --color=auto ovs
    root@1d0d709ed2c1:~/scripts#
