### ISSUE TITLE
"ipdk build --no-cache" completed successfully yet cannot start/attach

### ISSUE THREAD

**Issue by asafravid** [ipdk-io/ipdk#87]
Seems successful completion of build, yet the docker start fails.

What am I (or is) missing?

    make[3]: Leaving directory '/root/P4-OVS'
    make[2]: Leaving directory '/root/P4-OVS'
    make[1]: Leaving directory '/root/P4-OVS'
    Copy p4ovs_env_setup.sh script from P4-OVS
    Copy build-p4ovs.sh script from P4-OVS
    Copy install_dep_packages.sh script from P4-OVS
    Removing P4-OVS source code
    Removing p4-driver source code
    Removing P4C source code
    Removing intermediate container 72a75ce8c730
     ---> 5e845a1db81b
    Successfully built 5e845a1db81b
    Successfully tagged ipdk/p4-ovs-ubuntu20.04:92532fd
    ~/ipdk/build
    ~/ipdk/build# ./ipdk start -d
    Loaded /root/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    Unable to find image 'ipdk/p4-ovs-ubuntu20.04:92532fd' locally
    docker: Error response from daemon: pull access denied for ipdk/p4-ovs-ubuntu20.04, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
    See 'docker run --help'.
    ~/ipdk/build# docker images
    REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
    root@kub-node1-smadarf:~/ipdk/build# docker volume ls
    DRIVER    VOLUME NAME
    ~/ipdk/build#

**Comment by stolsma** [comment]
Looks like the build was ok and docker correctly tagged the created image but docker didn't write the image layers to the local image registry. Storage space problem?

Also, when you did `./ipdk install` it is preferred to use `ipdk start -d` without the `./`

**Comment by asafravid** [comment]
@stolsma the storage space max size is 10 GB
I'll try to increase to 20G and also `watch` the `df -h` during the build
I'll use `ipdk start -d`
thanks, I'll update

**Comment by asafravid** [comment]
Looks like its not a storage issue. I will need to check whats inside `ipdk start -d` and why it cannot find the image

    libtool: install: /usr/bin/install -c vtep/vtep-ctl /usr/local/bin/vtep-ctl
    make[3]: Leaving directory '/root/P4-OVS'
    make[2]: Leaving directory '/root/P4-OVS'
    make[1]: Leaving directory '/root/P4-OVS'
    Copy p4ovs_env_setup.sh script from P4-OVS
    Copy build-p4ovs.sh script from P4-OVS
    Copy install_dep_packages.sh script from P4-OVS
    Removing P4-OVS source code
    Removing p4-driver source code
    Removing P4C source code
    Removing intermediate container 4b3b37a68ca5
     ---> 7e61ca3bdeff
    Successfully built 7e61ca3bdeff
    Successfully tagged ipdk/p4-ovs-ubuntu20.04:92532fd
    ~/ipdk/build
    root@kub-node1-smadarf:~/ipdk/build# ipdk start -d
    Loaded /root/ipdk/build/scripts/ipdk_default.env
    Loaded /root/.ipdk/ipdk.env
    Unable to find image 'ipdk/p4-ovs-ubuntu20.04:92532fd' locally
    docker: Error response from daemon: pull access denied for ipdk/p4-ovs-ubuntu20.04, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
    See 'docker run --help'.
    root@kub-node1-smadarf:~/ipdk/build#

Images are:

    ~/ipdk/build# docker images
    REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
    <none>       <none>    3b5446026c42   12 hours ago   66.5MB
    <none>       <none>    8412087184f2   12 hours ago   66.5MB
    ~/ipdk/build#

@stolsma other ideas/suggestions?

**Comment by asafravid** [comment]
I see no volumes present:

    ~/ipdk/build# docker volume ls
    DRIVER    VOLUME NAME

**Comment by asafravid** [comment]
Maybe the problem is that the images are not tagged?
Can they be tagged now somehow?

    ~/ipdk/build# docker images
    REPOSITORY   TAG       IMAGE ID       CREATED        SIZE
    <none>       <none>    3b5446026c42   13 hours ago   66.5MB
    <none>       <none>    8412087184f2   13 hours ago   66.5MB
    ~/ipdk/build#

**Comment by asafravid** [comment]
I woul expect that since there's a log of

    Successfully tagged ipdk/p4-ovs-ubuntu20.04:92532fd

The some image would have been tagged as such right?

**Comment by asafravid** [comment]
I believe the `ipdk.env` which contains the image name - is properly configured - right?
 
    ~/ipdk/build# cat /root/.ipdk/ipdk.env
    #
    # IPDK CLI configuration file
    # See for more information https://github.com/ipdk-io/ipdk/blob/main/build/IPDK_Container/README_DOCKER.md#CLI-configuration-settings
    #
    # /root/ipdk/build/scripts contains the location of the 'sourcing' ipdk script when read.
    #
    BASE_IMG=ubuntu:20.04
    IMAGE_NAME=ipdk/p4-ovs-ubuntu20.04
    DOCKERFILE=${SCRIPT_DIR}/../Dockerfile.ubuntu

**Comment by stolsma** [comment]
> I see no volumes present:
> 
> ```
> ~/ipdk/build# docker volume ls
> DRIVER    VOLUME NAME
> ```

That s correct, the ipdk cli doesn't use docker volumes any more. It uses `~/.ipdk/volume` as root for the `/tmp` volume reference so that's why you don't see a docker volume any more.

**Comment by stolsma** [comment]
> I believe the `ipdk.env` which contains the image name - is properly configured - right?

Yep, thats correct

**Comment by stolsma** [comment]
> Maybe the problem is that the images are not tagged?
> Can they be tagged now somehow?

It looks like not all layers of the image are written to the docker image store and because the last layer is missing it doesn't tag the final image reference. Don't know why that happens... Most of the time that is a not enough memory or storage problem.

**Comment by stolsma** [comment]
> other ideas/suggestions?

Nope...

**Comment by asafravid** [comment]
@stolsma 
I now have managed to see the image and can `ipdk start -d` and `ipdk connect`.
However, within the `ipdk` container, upon `ps -ef | grep ovs` I do not see neither the `ovsdb-server` nor the `ovs-vswitchd` running.

How can I start those manually?

    root@43fdac434918:~/scripts# ps -ef | grep ovs
    root     23140    34  0 00:16 pts/1    00:00:00 grep --color=auto ovs
    root@43fdac434918:~/scripts# which ovsdb-server
    /usr/local/sbin/ovsdb-server
    root@43fdac434918:~/scripts# /usr/local/sbin/ovsdb-server
    ovsdb-server: I/O error: /usr/local/etc/openvswitch/conf.db: open failed (No such file or directory)
    root@43fdac434918:~/scripts# which ovs-vswitchd
    /usr/local/sbin/ovs-vswitchd
    root@43fdac434918:~/scripts# /usr/local/sbin/ovs-vswitchd
    /usr/local/sbin/ovs-vswitchd: error while loading shared libraries: libtarget_utils.so: cannot open shared object file: No such file or directory
    root@43fdac434918:~/scripts#

**Comment by asafravid** [comment]
I see that the `scripts/start.sh` calls `scripts/set_hugepages.sh` which requies a minor change in my system
Closing for now as I think I've root caused it
